import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const p=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.TEST_URL||'http://127.0.0.1:5173')+'?mode=guided');await p.locator('#journey-next').waitFor();await p.screenshot({path:'/tmp/journey-opening.png',fullPage:true});
 const next=()=>p.locator('#journey-next').click();
 const move=()=>p.getByRole('button',{name:/^Zug ausführen:/}).click();
 const rate=async(i=0)=>{await p.locator('#journey-reason').fill('Ich stütze mich auf Julies eigene Entscheidung und die Grenzen des beobachteten Verhaltens.');};
 assert.equal(await p.locator('#journey-next').isDisabled(),true);await move();await move();await next();await rate();await next();
 await p.getByRole('button',{name:'Mechanik untersuchen',exact:true}).click();assert.equal(await p.locator('#journey-next').isDisabled(),true);await p.getByRole('button',{name:'Das System vollständig öffnen'}).click();await next();await rate(1);await next();
 await p.getByRole('button',{name:'Mit Schmuck überzeugen',exact:true}).click();await move();await next();assert.match(await p.locator('#scene-controls').innerText(),/Zustimmung gewinnt sie dadurch nicht/);await next();
 await p.getByRole('button',{name:'Zuerst Julie informieren',exact:true}).click();await p.reload();await next();assert.equal(await p.getByRole('button',{name:'Carl übernimmt den Kasten',exact:true}).isDisabled(),true);await p.getByRole('button',{name:'Julie um die Information bitten'}).click();await p.getByRole('button',{name:'Carl übernimmt den Kasten',exact:true}).click();await next();
 await p.getByRole('button',{name:'Julie eigenmächtig zu Balken verschieben'}).click();assert.match(await p.locator('#status').innerText(),/nicht ohne mich/);assert.equal(await p.locator('#journey-next').isDisabled(),true);await p.getByRole('button',{name:'Julie selbst nach ihrer Wahl fragen'}).click();await move();await p.screenshot({path:'/tmp/journey-julie.png',fullPage:true});await next();await rate(2);await next();await move();await move();await next();await rate(0);await next();
 for(let i=0;i<3;i++)await move();await next();await rate(1);await next();await rate(1);await next();
 await p.getByText('Ohne Modellzugang: redaktionellen Text vergleichen',{exact:true}).click();await p.getByRole('button',{name:'Redaktionellen Vergleichstext verwenden'}).click();assert.match(await p.locator('.origin-label').innerText(),/keine KI-Inferenz/);await next();await rate(2);assert.equal(await p.locator('#journey-next').isDisabled(),true);for(const name of ['Sprache','Beleg','Schlussfolgerung'])await p.getByRole('button',{name,exact:true}).click();await next();for(const name of ['Daten','Training','Inferenz'])await p.getByRole('button',{name:name+' untersuchen',exact:true}).click();await next();await rate(1);await next();assert.match(await p.locator('#title').innerText(),/Brett deiner Urteile/);assert.match(await p.locator('#scene-controls').innerText(),/keine KI-Inferenz/);
 const download=p.waitForEvent('download');await p.getByRole('button',{name:'Meine Zugspur als Text sichern'}).click();const file=await download;assert.match(file.suggestedFilename(),/zugspur/);
 await p.locator('#archive-mode').click();assert.equal(await p.locator('#timeline button').count(),4);await p.locator('#guided-mode').click();assert.match(await p.locator('#title').innerText(),/Brett deiner Urteile/);
 await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/tmp/journey-ending-mobile.png',fullPage:true});await p.locator('#journal-button').click();assert.ok(await p.locator('#notebook').isVisible());await p.keyboard.press('Escape');
 assert.deepEqual(errors,[]);console.log('PASS: full guided journey, locks, information branch, consent, refresh/resume, evidence gates, labelled fallback, export, archive switch and mobile.');
}finally{await browser.close();}
