import {test} from 'node:test';
import assert from 'node:assert/strict';
import {stages,pages,roles,freshState,act,restore,canAdvance} from '../src/play-state.js';
import {checkpoints,checkpoint,assignedPerspective,constellation,latestClaims,facts,availableFacts} from '../src/dramaturgy.js';
import {createRoom,updateRoom,snapshot} from '../multiplayer/room.js';
import {claim} from './perspective-helpers.mjs';
test('Fourteen grounded checkpoints cover all four acts and eleven evidence events have exact sources',()=>{assert.equal(Object.keys(checkpoints).length,14);assert.deepEqual([...new Set(Object.values(checkpoints).map(c=>c.act))],[1,2,3,4]);for(const f of facts){assert.ok(pages[f.page].text.slice(f.start,f.end).length>12);assert.ok(f.access.includes(0));}const before=stages.find(s=>s.id==='text-4-1-0');const after=stages.find(s=>s.act===4&&s.scene===2&&s.part===s.parts);assert.ok(!availableFacts(before,0).some(f=>f.label.startsWith('Carl steigt')));assert.ok(availableFacts(after,0).find(f=>f.label.startsWith('Carl steigt')).known);assert.equal(availableFacts(after,1).find(f=>f.label.startsWith('Carl steigt')).known,false);});
test('Evidence validation, revisions, restoration and spatial meaning',()=>{const index=stages.findIndex(s=>checkpoint(s));let s={...freshState(),step:index,opened:true};const stage=stages[index];for(const bad of [{page:78},{start:-1},{end:999999},{perspective:99},{reason:''},{from:3,to:3}])assert.equal(act(s,claim(stage,3,bad)).changed,false);s=act(s,claim(stage)).state;const first=s.interpretations[0];assert.equal(act(s,claim(stage,3,{revises:first.id})).changed,false);const later=stages.findIndex((s,i)=>i>index&&checkpoint(s));s.step=later;s=act(s,claim(stages[later],3,{effect:'approach',revises:first.id})).state;assert.equal(s.interpretations.length,2);assert.equal(latestClaims(s.interpretations).length,1);const then=constellation(s.interpretations,3,roles,index),now=constellation(s.interpretations,3,roles);assert.notEqual(then.positions.get(1),now.positions.get(1));assert.equal(constellation(s.interpretations,7,roles).claims.length,0);assert.deepEqual(restore(JSON.stringify(s)),s);assert.equal(restore(JSON.stringify({...s,interpretations:[{...first,page:78}]})),null);});
test('Private independent perspectives, author integrity, delayed comparison and stale events',()=>{const r=createRoom('a','A',0,'play');const send=(id,e)=>updateRoom(r,id,{...e,step:r.state.step,epoch:r.epoch,revision:r.revision},1);send('b',{type:'join',name:'B'});send('a',{type:'start'});r.state.step=stages.findIndex(s=>checkpoint(s));r.state.opened=true;const stage=stages[r.state.step];send('a',claim(stage,assignedPerspective(stage,0),{author:'b',name:'Forged'}));assert.equal(r.state.interpretations[0].author,'a');assert.equal(snapshot(r,'b',1).state.interpretations.length,0);assert.throws(()=>send('a',{type:'compare',reason:'Eine noch nicht gemeinsam sichtbare Gegenüberstellung.'}));send('b',claim(stage,assignedPerspective(stage,1)));assert.equal(snapshot(r,'b',1).state.interpretations.length,2);assert.equal(snapshot(r,'a',1).perspectivesRevealed,true);assert.equal(snapshot(r,'a',1).complete,false);for(const id of ['a','b'])send(id,{type:'compare',reason:'Diese zwei Perspektiven unterscheiden sich in ihrem Urteil über die Beziehung.'});assert.equal(snapshot(r,'a',1).complete,true);send('a',{type:'undo'});assert.throws(()=>updateRoom(r,'b',{...claim(stage,assignedPerspective(stage,1)),step:r.state.step,epoch:0,revision:r.revision},1));});
