import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {pages,stages,freshState} from '../src/play-state.js';
import {checkpoint} from '../src/dramaturgy.js';
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try {const p=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const step=stages.findIndex(s=>checkpoint(s));await p.addInitScript(s=>{localStorage.setItem('schachmaschine-whole-play-v1',JSON.stringify(s));const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>setTimeout(()=>raf(cb),100);},{...freshState(),step});await p.goto(process.env.TEST_URL||'http://127.0.0.1:5173');await p.locator('#play-open').click();await p.locator('#workshop-toggle').click();
async function submit(pov,effect,text){await p.locator('#claim-perspective').selectOption(''+pov);await p.locator('#claim-effect').selectOption(effect);await p.locator('#claim-statement').fill(text);await p.locator('#claim-reason').fill('Die zitierte Formulierung deutet auf den Unterschied zwischen Wunsch und Durchsetzung hin.');await p.locator('#claim-quote').fill(stages[step].text.slice(0,120));await p.getByRole('button',{name:'Eingefügten Beleg zuordnen',exact:true}).click();await p.locator('#claim-save').click();}
await submit(3,'avoid','Julie entzieht sich der Erwartung der Baronin.');assert.equal(await p.locator('#play-next').isDisabled(),true);await submit(1,'control','Die Baronin versucht Julie eine Position zuzuweisen.');await p.locator('#perspective-compare').fill('Aus Julies Sicht ist die Erwartung fremd, aus Sicht der Baronin soll sie verpflichten.');await p.getByRole('button',{name:'Perspektivvergleich festhalten',exact:true}).click();assert.equal(await p.locator('#play-next').isDisabled(),false);
await p.locator('#perspective-select').selectOption('3');assert.match(await p.locator('#relation-list').textContent(),/Julie entzieht/);await p.locator('#perspective-select').selectOption('1');assert.match(await p.locator('#relation-list').textContent(),/Baronin versucht/);await p.locator('#perspective-layer').selectOption('knowledge');assert.match(await p.locator('#relation-list').textContent(),/noch keine Deutung/);await p.locator('#perspective-layer').selectOption('all');
for(const label of ['Draufsicht','Gegenseite','Von links','Von rechts','Nahansicht','Über die Schulter der Fokusfigur'])await p.locator('.perspective-camera').getByRole('button',{name:label,exact:true}).click();await p.locator('.perspective-camera').getByRole('button',{name:'Raumansicht',exact:true}).click();await p.locator('#perspective-select').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/perspectives-desktop.png'});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#perspective-select').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/perspectives-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS: grounded claims, two perspectives, comparison gate, filters, all camera views and mobile layout.');}finally{await browser.close();}
