import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {pages,stages,freshState,act,canAdvance,restore} from '../src/play-state.js';
import {createRoom,updateRoom,snapshot,actor} from '../multiplayer/room.js';
test('Every transcript character appears exactly once in chronological play order',()=>{assert.equal(pages.map(p=>p.text).join(''),fs.readFileSync(new URL('../public/sources/beck-1798-transkript.txt',import.meta.url),'utf8'));assert.equal(new Set(pages.filter(p=>p.act).map(p=>p.act+'-'+p.scene)).size,44);assert.equal(stages.filter(s=>s.kind==='reflection').length,4);assert.deepEqual([1,2,3,4].map(a=>new Set(pages.filter(p=>p.act===a).map(p=>p.scene)).size),[10,10,11,13]);});
test('Full solo play cannot skip unopened text or act reflections; saved state restores',()=>{let s=freshState();for(const stage of stages){if(stage.kind==='ending')break;assert.equal(act(s,{type:'next'}).changed,false);if(stage.kind==='text')s=act(s,{type:'open',role:stage.roleIndex}).state;else {s=act(s,{type:'record',reason:'Die Figur verschiebt die Handlungsmacht; mein Beleg steht im gelesenen Aufzug.'}).state;assert.equal(canAdvance(s),false);s=act(s,{type:'stage',role:3,to:'d4'}).state;}assert.ok(canAdvance(s));assert.deepEqual(restore(JSON.stringify(s)),s);s=act(s,{type:'next'}).state;}assert.equal(stages[s.step].id,'ending');assert.equal(Object.keys(s.records).length,4);assert.equal(restore(JSON.stringify({...s,step:99999})),null);});
for(const count of [2,5])test(`Full play with ${count} readers: roles, shared stage, private notes and all text`,()=>{const r=createRoom('0','Reader 0',0,'play');const send=(id,event)=>updateRoom(r,id,{...event,revision:r.revision,epoch:r.epoch,step:r.state.step},100);for(let i=1;i<count;i++)send(''+i,{type:'join',name:'Reader '+i});send('0',{type:'start'});for(const stage of stages){if(stage.kind==='ending')break;if(stage.kind==='text')send(actor(r),{type:'open',role:stage.roleIndex});else{send(actor(r),{type:'stage',role:3,to:'d4'});for(let i=0;i<count;i++){send(''+i,{type:'record',reason:'Eine eigene Beobachtung mit einem Beleg aus dem gelesenen Aufzug.'});if(i<count-1)assert.equal(snapshot(r,'0',100).comparisons[stage.id],undefined);}}for(let i=0;i<count;i++)send(''+i,{type:'ready',ready:true});send('0',{type:'next'});}assert.equal(stages[r.state.step].id,'ending');assert.equal(Object.keys(snapshot(r,'0',100).comparisons).length,4);send('0',{type:'undo'});assert.notEqual(stages[r.state.step].id,'ending');send('0',{type:'reset'});assert.equal(r.state.step,0);assert.equal(r.members.length,count);});

test('Full reading rooms last seven days; short rooms keep their one-day lifetime',()=>{assert.equal(createRoom('a','A',100,'play').expires,100+7*86400000);assert.equal(createRoom('a','A',100).expires,100+86400000);});
