import {readingText,editionFor} from '../src/text-edition.js';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {checkpoint} from '../src/dramaturgy.js';
import {stages,pages} from '../src/play-state.js';
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>setTimeout(()=>raf(cb),100);});await p.goto(process.env.TEST_URL||'http://127.0.0.1:5173');const next=()=>p.locator('#play-next').click();let count=0;
for(const stage of stages){if(stage.kind==='ending')break;if(stage.kind==='text'){assert.equal(await p.locator('#play-next').isDisabled(),true);await p.locator('#play-open').click();assert.equal(await p.locator('#staged-transcript').textContent(),readingText(stage));await p.locator('#section-summary').getByRole('button',{name:'Kurz zusammengefasst',exact:true}).click();assert.equal(await p.locator('.edition-summary>p').textContent(),editionFor(stage).summary);await p.keyboard.press('Escape');await p.locator('.edition-dialog').waitFor({state:'detached'});count++;if(count===2){await p.screenshot({path:'/tmp/play-stage.png',fullPage:true});await p.reload();assert.equal(await p.locator('#staged-transcript').textContent(),readingText(stage));await p.locator('#section-summary').getByRole('button',{name:'Kurz zusammengefasst',exact:true}).click();assert.equal(await p.locator('.edition-summary>p').textContent(),editionFor(stage).summary);await p.keyboard.press('Escape');await p.locator('.edition-dialog').waitFor({state:'detached'});await p.locator('#play-undo').click();assert.equal(await p.locator('#play-next').isDisabled(),true);await p.locator('#play-open').click();}if(checkpoint(stage)){if(!await p.locator('#interpretation-drawer').isVisible())await p.locator('#workshop-toggle').click();const pageIndex=pages.findIndex(x=>x.id===stage.id);for(const viewpoint of [3,1]){await p.locator('#claim-perspective').selectOption(''+viewpoint);await p.locator('#claim-statement').fill('Diese Figur widerspricht einer ihr fremden Erwartung.');await p.locator('#claim-reason').fill('Der Wortlaut macht für mich den Abstand zur fremden Absicht sichtbar.');await p.locator('#claim-quote').fill(stage.text.slice(0,100));await p.getByRole('button',{name:'Eingefügten Beleg zuordnen',exact:true}).click();await p.locator('#claim-save').click();}if([11,13].includes(checkpoint(stage).index)){await p.getByText(/Entwicklung der Lesarten ·/).click();await p.getByRole('button',{name:/Lesart #.*prüfen \/ revidieren/}).first().click();await p.locator('#claim-statement').fill('Die frühere Einschätzung bleibt bestehen, muss aber eingeschränkt werden.');await p.locator('#claim-reason').fill('Der spätere Textbeleg zeigt eine andere Wirkung derselben Beziehung.');await p.locator('#claim-quote').fill(stage.text.slice(0,100));await p.getByRole('button',{name:'Eingefügten Beleg zuordnen',exact:true}).click();await p.locator('#claim-save').click();}await p.locator('#perspective-compare').fill('Die Figuren haben unterschiedliche Absichten und unterschiedliche Informationen zur Verfügung.');await p.getByRole('button',{name:'Perspektivvergleich festhalten',exact:true}).click();}}else {assert.equal(await p.locator('#play-next').isDisabled(),true);await p.locator('#play-reason').fill('Julie erhält in meinem Regiezug eigenen Raum. Ich beziehe mich auf ihren Widerspruch gegen fremde Pläne.');}await next();}
assert.equal(count,pages.length);assert.match(await p.locator('#title').textContent(),/ganze Text/);await p.locator('#journal-button').click();const dl=p.waitForEvent('download');await p.getByRole('button',{name:'Lesestand als Datei sichern'}).click();assert.match((await dl).suggestedFilename(),/lesestand.json/);await p.keyboard.press('Escape');await p.locator('#guided-mode').click();await p.locator('#journey-next').waitFor();await p.locator('#play-mode').click();assert.match(await p.locator('#title').textContent(),/ganze Text/);p.on('dialog',d=>d.accept());await p.getByRole('button',{name:'Reset · Neu beginnen',exact:true}).click();await p.locator('#play-open').click();await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/tmp/play-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log(`PASS: all ${count} corrected reading pages and summaries, four staging/reflection gates, persistent resume, undo, export, modes, reset and mobile.`);}finally{await browser.close();}
