import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {stages,freshState} from '../src/play-state.js';
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const step=stages.findIndex(s=>s.id==='text-4-2-0');await p.addInitScript(state=>{if(!localStorage.getItem('schachmaschine-whole-play-v1'))localStorage.setItem('schachmaschine-whole-play-v1',JSON.stringify(state));},{...freshState(),step,opened:true});await p.goto(process.env.TEST_URL||'http://127.0.0.1:5173');await p.locator('#board-zoom').waitFor();const distance=()=>p.locator('#canvas').getAttribute('data-camera-distance').then(Number);
const setZoom=async value=>{await p.locator('#board-zoom').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input'));},String(value));await p.waitForTimeout(150);};await setZoom(320);const initial=await distance();assert.ok(Math.abs(initial-21/3.2)<.01);
for(const pov of ['1','3','7','0','13']){await p.locator('#perspective-select').selectOption(pov);await p.waitForTimeout(150);assert.ok(Math.abs(await distance()-initial)<.01,'distance preserved for '+pov);}
await p.getByRole('button',{name:'Draufsicht',exact:true}).last().click();assert.ok(Math.abs(await distance()-initial)<.01);await p.locator('#follow-perspective').check();await p.locator('#perspective-select').selectOption('5');assert.ok(Math.abs(await distance()-initial)<.01);
await setZoom(840);assert.ok(Math.abs(await distance()-2.5)<.01);await setZoom(40);assert.ok((await distance())>50);await p.getByRole('button',{name:'Zoom zurücksetzen',exact:true}).click();assert.ok(Math.abs(await distance()-21)<.01);
const c=p.locator('#canvas canvas');await c.hover();const before=await distance();await p.mouse.wheel(0,-300);await p.waitForTimeout(350);const wheeled=await distance();assert.ok(wheeled<before);await p.locator('#perspective-select').selectOption('13');await p.waitForTimeout(150);assert.ok(Math.abs(await distance()-wheeled)<.01);
await p.locator('#strategy-open').click();assert.ok(await p.locator('[data-profile="Erster Träger"]').isVisible());assert.ok(await p.locator('[data-profile="Zweiter Träger"]').isVisible());await p.locator('#inner-draft summary').click();await p.locator('[data-strategy-note="belief"]').fill('Die Träger können wissen, dass er der Unrechte ist, und ihn trotzdem tragen.');await p.locator('#inner-role').selectOption('3');await p.locator('#inner-role').selectOption('13');await p.locator('#inner-draft summary').click();assert.match(await p.locator('[data-strategy-note="belief"]').inputValue(),/Unrechte/);
await p.locator('[data-theory="room"] summary').click();assert.match(await p.locator('[data-theory="room"]').textContent(),/keine technische Vorstufe/);await p.locator('#turing-lab summary').first().click();await p.locator('[data-strategy-note="turing-question"]').fill('Welche Rückfrage würde die Rollenbehauptung widerlegen?');await p.locator('.strategy-close').click();await p.reload();await p.locator('#perspective-select').selectOption('13');await p.locator('#strategy-open').click();await p.locator('#inner-draft summary').click();assert.match(await p.locator('[data-strategy-note="belief"]').inputValue(),/Unrechte/);await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/tmp/strategy-mobile.png'});await p.locator('.strategy-close').click();await p.screenshot({path:'/tmp/strategy-board-mobile.png'});await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:'/tmp/strategy-board-desktop.png'});assert.deepEqual(errors,[]);console.log('PASS: range/wheel zoom persists across perspectives and camera views; expanded bounds, carrier perspectives, private notes, Turing workshop, mobile.');}finally{await browser.close();}
