const $ = s=>document.querySelector(s);
const esc = s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='schachmaschine-ermittlungsakte-v1';
const blank=()=>({version:1,current:'auftakt',missions:{},collected:[],events:[]});
let state=blank(),memoryOnly=false;
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch{memoryOnly=true;}
function validate(x){
 if(!x||x.version!==1||!x.missions||typeof x.missions!=='object'||Array.isArray(x.missions)||!Array.isArray(x.collected)||!Array.isArray(x.events))throw Error('Unpassendes Dateiformat');
 const clean=blank();clean.current=MISSIONS.some(m=>m.id===x.current)?x.current:'auftakt';
 const ids=new Set(MISSIONS.flatMap(m=>m.cards.map(c=>c[0])));clean.collected=[...new Set(x.collected.filter(id=>ids.has(id)))];
 for(const m of MISSIONS){const d=x.missions[m.id];if(!d||typeof d!=='object')continue;const t={};for(const k of ['claim','evidence','objection','revision','reading','confidence','initial','initialConfidence'])t[k]=typeof d[k]==='string'?d[k].slice(0,20000):'';t.actions=Array.isArray(d.actions)?d.actions.filter(a=>typeof a==='string').slice(0,100):[];if(Array.isArray(d.order)&&d.order.length===5&&new Set(d.order).size===5&&d.order.every(v=>Number.isInteger(v)&&v>=0&&v<5))t.order=[...d.order];t.done=d.done===true;t.history=Array.isArray(d.history)?d.history.filter(h=>h&&typeof h==='object').slice(-30).map(h=>({at:String(h.at||''),claim:String(h.claim||'').slice(0,20000),evidence:String(h.evidence||'').slice(0,20000),objection:String(h.objection||'').slice(0,20000),revision:String(h.revision||'').slice(0,20000)})):[];clean.missions[m.id]=t;}
 clean.events=x.events.filter(e=>e&&typeof e==='object').slice(-500).map(e=>({at:String(e.at||''),mission:String(e.mission||''),action:String(e.action||'')}));return clean;
}
function data(m=mission()){return state.missions[m.id] ||= {actions:[],history:[]};}
function mission(){return MISSIONS.find(m=>m.id===state.current)||MISSIONS[0];}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));memoryOnly=false;}catch{memoryOnly=true;}$('#storage').textContent=memoryOnly?'Nur in dieser Sitzung verfügbar – Akte exportieren.':'Automatisch auf diesem Gerät gespeichert. Export sichert deine Akte.';}
function log(action){state.events.push({at:new Date().toISOString(),mission:state.current,action});state.events=state.events.slice(-500);save();}
function action(id){const d=data();if(!d.actions.includes(id)){d.actions.push(id);log(id);}updateProgress();}
function msg(s){$('#notice').textContent=s;}
function updateProgress(){const done=MISSIONS.filter(m=>data(m).done).length;$('#progress').textContent=`${done} / ${MISSIONS.length} Fallakten · ${state.collected.length} / 36 Beweisstücke`;$('#meter').value=done;$('#rank').textContent=done===12?'Ermittlung dokumentiert':done>=8?'Gegenargumente prüfen':done>=4?'Zusammenhänge rekonstruieren':'Spuren aufnehmen';renderMap();}
function renderMap(){const map=$('#map');map.replaceChildren();for(let r=8;r>=1;r--)for(let f=0;f<8;f++){const sq='abcdefgh'[f]+r,m=MISSIONS.find(m=>m.square===sq);const el=document.createElement(m?'button':'span');el.className='square '+((f+r)%2?'dark':'light');if(m){el.innerHTML=`<span class="piece">${m.icon}</span><small>${sq.toUpperCase()}${data(m).done?' ✓':''}</small>`;el.title=m.title;el.setAttribute('aria-label',`${sq}: ${m.title}${data(m).done?' · dokumentiert':''}`);el.setAttribute('aria-current',String(m.id===state.current));el.onclick=()=>navigate(m.id);}else el.setAttribute('aria-hidden','true');map.append(el);}}
function navigate(id){state.current=id;save();render();$('#mission-title').focus();}
function sourcesHtml(ids){return ids.map(id=>{const s=SOURCES.find(s=>s.id===id);return `<a target="_blank" rel="noopener" href="${s.url}">[${s.id}] ${esc(s.title)} ↗</a>`;}).join('<br>');}
function render(){const m=mission(),d=data();$('#era').textContent=m.era+' · Feld '+m.square.toUpperCase();$('#mission-title').textContent=m.title;$('#subtitle').textContent=m.subtitle;$('#intro').textContent=m.intro;
 $('#knowledge').innerHTML=m.knowledge.map(([h,p])=>`<section><h3>${esc(h)}</h3><p>${esc(p)}</p></section>`).join('')+`<div class="source-links">${sourcesHtml(m.sources)}</div>`;
 $('#cards').innerHTML=m.cards.map(c=>`<article class="card"><small>${esc(c[0])} · ${esc(c[3])}</small><h3>${esc(c[1])}</h3><p>${esc(c[2])}</p><button data-card="${c[0]}" aria-pressed="${state.collected.includes(c[0])}">${state.collected.includes(c[0])?'✓ In der Akte':'Beweisstück sichern'}</button></article>`).join('');
 $('#cards').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!state.collected.includes(b.dataset.card)){state.collected.push(b.dataset.card);log('Beweis '+b.dataset.card);}b.textContent='✓ In der Akte';b.setAttribute('aria-pressed','true');updateProgress();});
 $('#task').textContent=m.task;$('#questions').innerHTML=m.questions.map(q=>`<li>${esc(q)}</li>`).join('');$('#challenge').textContent=m.challenge;$('#bridge').textContent=m.bridge;
 $('#fields').innerHTML=[['claim',m.kind==='final'?'Dein Gutachten / Urteil':'Deine begründete These'],['evidence','Belege mit Karten-ID / Quelle / Fundstelle'],['objection','Der stärkste Einwand gegen deine These'],['revision','Was müsste geschehen, damit du dein Urteil änderst?']].map(([id,label])=>`<label>${label}<textarea id="field-${id}" data-field="${id}" rows="${id==='claim'?5:3}" maxlength="20000">${esc(d[id]||'')}</textarea></label>`).join('');
 $('#fields').querySelectorAll('textarea').forEach(t=>t.oninput=()=>{d[t.dataset.field]=t.value;save();});
 $('#history').innerHTML=d.history?.length?`<summary>${d.history.length} gesicherte Fassung(en)</summary>`+d.history.map(h=>`<p><small>${esc(h.at)}</small><br>${esc(h.claim)}<br><em>Einwand:</em> ${esc(h.objection)}</p>`).join(''):'<summary>Noch keine gesicherte Fassung</summary>';
 $('#complete').textContent=d.done?'Überarbeitete Fassung sichern':'Fallakte abschliessen';$('#done-note').textContent=d.done?'Dokumentiert · '+m.badge:'';$('#notice').textContent='';renderExperiment(m,d);renderOriginal(m,d);updateProgress();save();
}
function renderOriginal(m,d){const o=ORIGINALS[m.id],root=$('#original');root.hidden=!o;if(!o){root.replaceChildren();return;}root.innerHTML=`<h2>${o.title}</h2><p>${o.edition}</p><a class="primary linkbutton" href="${o.url}" target="_blank" rel="noopener">Englisches Original öffnen ↗</a>${o.alternate?` <a href="${o.alternate}" target="_blank" rel="noopener">Englische HTML-Vorfassung ↗</a>`:''}`+o.passages.map(p=>`<section><h3>${esc(p.ref)}</h3>${p.quote?`<blockquote lang="en">${esc(p.quote)}</blockquote>`:''}<p>${esc(p.task)}</p></section>`).join('')+`<p>${esc(o.reading)}</p><details><summary>Sprachhilfe</summary><p>${esc(o.vocabulary)}</p></details><label>Deine Beobachtung am englischen Wortlaut (mit Fundstelle)<textarea id="reading-note" rows="4">${esc(d.reading||'')}</textarea></label>`;$('#reading-note').oninput=e=>{d.reading=e.target.value;save();};}
function renderExperiment(m,d){const root=$('#experiment');root.innerHTML='';const b=(text,fn)=>{const button=document.createElement('button');button.textContent=text;button.onclick=fn;root.append(button);return button;};const p=text=>{const el=document.createElement('p');el.textContent=text;root.append(el);return el;};
 if(m.kind==='prediction'){root.innerHTML=`<label>Erste Hypothese vor deiner Untersuchung<textarea id="initial" rows="3">${esc(d.initial||'')}</textarea></label><label>Wie sicher bist du? <output id="confidence-out">${esc(d.confidence||'50')} %</output><input id="confidence" type="range" min="0" max="100" step="5" value="${esc(d.confidence||'50')}"></label>`;$('#initial').oninput=e=>{if(!d.actions.includes('prediction')){d.initial=e.target.value;save();}};$('#initial').readOnly=d.actions.includes('prediction');$('#confidence').oninput=e=>{d.confidence=e.target.value;$('#confidence-out').textContent=e.target.value+' %';save();};b('Erste Hypothese festhalten',()=>{if(d.actions.includes('prediction'))return msg('Deine erste Hypothese bleibt unverändert. Verwende für spätere Urteile die These unten.');if(!d.initial?.trim())return msg('Schreibe zuerst deine Hypothese.');d.initialConfidence=d.confidence||'50';action('prediction');$('#initial').readOnly=true;msg('Erste Hypothese gesichert. Deine spätere These bleibt frei veränderbar.');});}
 if(m.kind==='cabinet'){p('Schematischer Versuch: Der Operator kann vor jedem einzelnen Blick seinen Ort wechseln.');const chambers=document.createElement('div');chambers.className='chambers';root.append(chambers);for(let i=0;i<3;i++){const cell=document.createElement('button');cell.textContent='Fenster '+(i+1);cell.onclick=()=>{chambers.querySelectorAll('button').forEach((c,j)=>c.textContent=j===i?'Leer sichtbar':'Blick gesperrt');action('window'+i);msg('Dieses Fenster zeigt jetzt einen leeren Raum. Die anderen Räume sind nicht sichtbar.');};chambers.append(cell);}b('Gleichzeitig prüfen',()=>{chambers.querySelectorAll('button').forEach((c,i)=>c.textContent=i===1?'♟ Operator sichtbar':'Leer sichtbar');action('simultaneous');msg('Unter der neuen Versuchsbedingung wird die Person sichtbar. Dies ist ein didaktisches Modell.');});}
 if(m.kind==='sequence'){const order=d.order||[2,0,4,1,3];const list=document.createElement('ol');list.className='sequence';root.append(list);const draw=()=>{list.innerHTML=order.map((idx,pos)=>`<li><span>${esc(m.sequence[idx])}</span><button data-up="${pos}" ${pos===0?'disabled':''} aria-label="${esc(m.sequence[idx])} nach oben">↑</button><button data-down="${pos}" ${pos===4?'disabled':''} aria-label="${esc(m.sequence[idx])} nach unten">↓</button></li>`).join('');list.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{const up=btn.hasAttribute('data-up'),pos=Number(up?btn.dataset.up:btn.dataset.down),other=pos+(up?-1:1);[order[pos],order[other]]=[order[other],order[pos]];d.order=order;save();draw();});};draw();b('Wirkungskette prüfen',()=>{if(order.every((v,i)=>v===i)){action('sequence');msg('Die Kette stimmt im vereinfachten Modell. Begründe jetzt den Ort der Entscheidung.');}else msg('Prüfe: Erst kommt ein Signal von aussen, dann wird ein Gegenzug ausgewählt und schliesslich ausgeführt.');});}
 if(m.kind==='probe'){p('Kontrollsystem: Eingabe 2 + 2. Der folgende fest programmierte Schalter gibt absichtlich 5 aus.');b('Fehler erzeugen',()=>{p('Ausgabe: 5. Herkunft: feste Programmanweisung, kein menschlicher Live-Operator.');action('counterexample');msg('Ein Fehler allein identifiziert die Ursache nicht. Der Versuch widerlegt keine andere historische Beobachtung.');});}
 if(m.kind==='network'){const view=p('Baronin → Balken: Plan bekannt. Sophie: kennt den Plan. Carl: kein Informationszugang in diesem vereinfachten Modell.');b('Sophies Mitteilung weitergeben',()=>{view.textContent='Sophie → Carl und Julie: Kastenplan bekannt. Carl kann nun seine Übernahme vorbereiten. Im Original steigt er in IV, 2 in den ersten Kasten.';action('informed');});b('Mitteilung zurückhalten · Spielvariante',()=>{view.textContent='Spielvariante: Der Informationsweg ist unterbrochen. Carls dokumentierter Eingriff lässt sich aus diesem Modell nicht mehr herleiten. Andere Entwicklungen bleiben denkbar.';action('withheld');});}
 if(m.kind==='turing'){const box=p('Antwort A: «Ich würde zuerst prüfen, ob deine Voraussetzung stimmt.» Etikett: Mensch. Antwort B: «Ich bin mir nicht sicher. Zeig mir bitte den Beleg.» Etikett: Maschine.');b('Herkunftsetiketten vertauschen',()=>{box.textContent='Antwort A: «Ich würde zuerst prüfen, ob deine Voraussetzung stimmt.» Etikett: Maschine. Antwort B: «Ich bin mir nicht sicher. Zeig mir bitte den Beleg.» Etikett: Mensch. Beide Antworten bleiben redaktionell verfasst; nur die Etiketten wurden vertauscht.';action('labels');});}
 if(m.kind==='symbols'){const rules=[['◇','○'],['○','△'],['△','◇']];p('Regelbuch: ◇ → ○   ·   ○ → △   ·   △ → ◇');let n=d.actions.filter(x=>/^symbol[0-2]$/.test(x)).length;const label=document.createElement('label');const input=document.createElement('input');input.type='text';input.maxLength=8;input.setAttribute('aria-label','Ausgabesymbol');const prompt=document.createElement('span');label.append(prompt,input);root.append(label);const draw=()=>{prompt.textContent=n<3?`Sendung ${n+1}: ${rules[n][0]} – tippe oder kopiere das passende Ausgabesymbol.`:'Drei Sendungen bearbeitet. Wer versteht hier was?';input.disabled=n===3;};draw();b('Sendung abgeben',()=>{if(n===3)return;if(input.value.trim()===rules[n][1]){action('symbol'+n);n++;input.value='';draw();msg('Regelgerecht zugeordnet. Das Urteil über Verstehen bleibt offen.');}else msg('Die Form passt noch nicht zur Regel. Kopiere bei Bedarf das Symbol aus dem Regelbuch.');});}
 if(m.kind==='pipeline'){const display=p('Wähle einen Prozess.');for(const [id,title,text]of [['historical','Scheinautomat','Gegenzug → verborgener Mensch → Gestänge → sichtbarer Zug.'],['platform','Arbeitsplattform','Auftrag → Vermittlung → menschliche Bearbeitung → Ergebnis.'],['model','Trainiertes Modell','Voraussetzungen: Daten + Verfahren + menschliche Beiträge. Aktueller Vorgang: Eingabe → Modellberechnung → Ausgabe.']])b(title,()=>{display.textContent=text;action(id);});}
 if(['evidence','perspective','archive','final'].includes(m.kind)){p(m.kind==='final'?'Öffne deine Akte und wähle mindestens drei Beweisstücke aus verschiedenen Fällen. Das Endspiel bleibt auch im freien Erkunden erreichbar.':'Hier ist deine Handlung eine Textuntersuchung: sichere Beweisstücke und entwickle eine begründete Gegenlesart.');b('Belege miteinander konfrontieren',()=>{action('confront');msg('Nutze die Felder unten: These, genauer Beleg, Gegenargument und Revisionsbedingung.');});}
 if(m.kind==='final'){const first=data(MISSIONS[0]);p('Deine erste Hypothese: '+(first.initial||'Noch nicht festgehalten.')+' · damalige Sicherheit: '+(first.initialConfidence||'—')+' %.');}
}
function requirements(m,d){const needed={prediction:['prediction'],cabinet:['window0','window1','window2','simultaneous'],sequence:['sequence'],probe:['counterexample'],network:['informed','withheld'],turing:['labels'],symbols:['symbol0','symbol1','symbol2'],pipeline:['historical','platform','model']};if((needed[m.kind]||['confront']).some(a=>!d.actions.includes(a)))return 'Führe zuerst die Untersuchungsschritte dieser Station aus.';
 if(m.cards.filter(c=>state.collected.includes(c[0])).length<2)return 'Sichere mindestens zwei Beweisstücke dieser Station.';
 for(const k of ['claim','evidence','objection','revision'])if(!d[k]?.trim())return 'Fülle These, Belege, Gegenargument und Revisionsbedingung aus.';
 if(ORIGINALS[m.id]&&!d.reading?.trim())return 'Halte noch eine Beobachtung am englischen Original mit Fundstelle fest.';
 if(m.kind==='final'){const referenced=MISSIONS.filter(x=>x.id!==m.id&&x.cards.some(c=>new RegExp('\\b'+c[0]+'\\b').test(d.evidence||'')));if(referenced.length<3)return 'Nenne im Belegfeld Karten-IDs aus mindestens drei anderen Stationen (z. B. A1, B2, S3).';}return null;}
$('#complete').onclick=()=>{const m=mission(),d=data(),error=requirements(m,d);if(error)return msg(error);d.history||=[];d.history.push({at:new Date().toISOString(),claim:d.claim,evidence:d.evidence,objection:d.objection,revision:d.revision});d.done=true;log('Fassung gesichert');render();msg('Gesichert. Geprüft wurde die Vollständigkeit, nicht die Qualität oder Richtigkeit deiner Deutung.');};
$('#next').onclick=()=>navigate(MISSIONS[(MISSIONS.findIndex(m=>m.id===state.current)+1)%MISSIONS.length].id);
function openDialog(title,html){$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
$('#close-dialog').onclick=()=>$('#dialog').close();
$('#teaching-guide').onclick=()=>openDialog('Unterricht & Spielwege',TEACHING_GUIDE);
$('#archive').onclick=()=>openDialog('Quellen und Begriffe',`<p>Quellenstand: 30. September 2026. Deutsche Einführungen sind redaktionelle Erläuterungen. Bei Poe und Searle gehören die englischen Originale zur Aufgabe.</p>`+SOURCES.map(s=>`<article><h3>[${s.id}] ${esc(s.title)} · ${s.year}</h3><small>${esc(s.type)}</small><p>${esc(s.note)}</p><a href="${s.url}" target="_blank" rel="noopener">Ressource öffnen ↗</a></article>`).join('')+'<h2>Begriffe</h2>'+GLOSSARY.map(([t,d])=>`<details><summary>${esc(t)}</summary><p>${esc(d)}</p></details>`).join(''));
$('#journal').onclick=()=>openDialog('Deine Ermittlungsakte',`<p>${state.collected.length} gesicherte Beweisstücke. Entwürfe und abgeschlossene Fassungen bleiben unterscheidbar.</p>`+MISSIONS.map(m=>{const d=data(m);return `<article><h3>${m.icon} ${esc(m.title)} ${d.done?'✓':''}</h3><p>${esc(d.claim||'Noch kein Urteil.')}</p><p><strong>Belege:</strong> ${esc(d.evidence||'—')}</p><p><strong>Einwand:</strong> ${esc(d.objection||'—')}</p><p><strong>Revision:</strong> ${esc(d.revision||'—')}</p>${d.reading?`<p><strong>Englische Lektüre:</strong> ${esc(d.reading)}</p>`:''}</article>`;}).join(''));
$('#help').onclick=()=>openDialog('So spielst du',`<p>Du untersuchst zwölf Fälle auf einem Schachfeld. Die Koordinaten sind Zugänge zu Missionen, keine vorgeschriebene legale Schachpartie. Du brauchst keine Schachkenntnisse.</p><ol><li>Wähle eine Figur und lies den Auftrag.</li><li>Führe das Experiment oder die Textuntersuchung aus.</li><li>Sichere mindestens zwei Beweisstücke.</li><li>Formuliere These, Beleg, Einwand und Revisionsbedingung.</li><li>Schliesse die Akte ab. Du kannst jederzeit eine neue Fassung sichern.</li></ol><p>Abzeichen dokumentieren bearbeitete Fälle. Die Software prüft formale Vollständigkeit, keine philosophische oder literarische Qualität. Alle Stationen bleiben offen. Es gibt kein Zeitlimit, keine Rangliste und keine Multiple-Choice-Fragen.</p><h3>Gemeinsam spielen</h3><p>Zu zweit bis fünft an einem Gerät: verteilt Ermittlung, Quellenprüfung, Gegenrede, Regie und Protokoll. Wechselt die Rollen nach jeder Station. Jede abweichende Meinung gehört in die Akte. Dieses Modul hat keinen eigenen Online-Multiplayer.</p><h3>Zeit</h3><p>Kurzroute: Auftakt, Bühne, Zeichenbüro, Tribunal (etwa 60–90 Minuten). Vollständige Untersuchung mit Originallektüre: etwa 3–5 Lektionen, bei ausführlicher Lektüre länger. Richtwerte, kein Zeitlimit.</p>`);
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=()=>download('Meine_Ermittlungsakte.json',JSON.stringify(state,null,2),'application/json');
$('#export-text').onclick=()=>{const text=['DIE SCHACHMASCHINE · ERMITTLUNGSAKTE',new Date().toISOString(),'Erste Hypothese: '+(data(MISSIONS[0]).initial||'—'),...MISSIONS.map(m=>{const d=data(m);return `\n${m.title} · ${d.done?'dokumentiert':'Entwurf'}\nThese: ${d.claim||'—'}\nBelege: ${d.evidence||'—'}\nEinwand: ${d.objection||'—'}\nRevisionsbedingung: ${d.revision||'—'}\nEnglische Originallektüre: ${d.reading||'—'}\nFrühere Fassungen: ${JSON.stringify(d.history||[])}`;})].join('\n');download('Meine_Ermittlungsakte.txt',text,'text/plain;charset=utf-8');};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Die Datei ist zu gross.');const next=validate(JSON.parse(await file.text()));if(!confirm('Den aktuellen Stand durch die gewählte Akte ersetzen? Exportiere ihn vorher, falls du ihn behalten willst.'))return;state=next;save();render();msg('Akte geladen.');}catch(err){msg('Import nicht möglich: '+err.message);}finally{e.target.value='';}};
$('#reset').onclick=()=>{if(confirm('Alle Einträge dieser Ermittlungsakte auf diesem Gerät löschen? Die Hauptinstallation bleibt unberührt.')){state=blank();save();render();}};
const requested=new URLSearchParams(location.search).get('station');if(MISSIONS.some(m=>m.id===requested))state.current=requested;
$('#mission-select').innerHTML=MISSIONS.map(m=>`<option value="${m.id}">${m.square.toUpperCase()} · ${m.title}</option>`).join('');$('#mission-select').onchange=e=>navigate(e.target.value);
// Connection to the reading installation; the case file remains usable on its own.
const SCENE_LINKS={buehne:[[3,1],[3,5],[4,11]],intrige:[[3,5],[3,8],[4,2],[4,11],[4,13]],julie:[[3,3],[4,9],[4,10]]};
const embedded=window.parent!==window;
const returnButton=document.createElement('button');returnButton.textContent=embedded?'Zurück zum Spiel':'Zur Bühneninstallation';returnButton.id='return-to-play';returnButton.onclick=()=>{if(embedded)parent.postMessage({type:'schach-investigation-close'},location.origin);else location.href='../';};document.querySelector('nav').prepend(returnButton);
window.addEventListener('message',e=>{if(!embedded||e.source!==parent||e.origin!==location.origin)return;if(e.data?.type==='schach-investigation-station'&&MISSIONS.some(m=>m.id===e.data.station))navigate(e.data.station);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')&&embedded){e.preventDefault();parent.postMessage({type:'schach-investigation-close'},location.origin);}});
function renderSceneLinks(){const id=mission().id,links=SCENE_LINKS[id]||[];if(!links.length)return;const section=document.createElement('section');section.className='panel';section.id='beck-context';const h=document.createElement('h3');h.textContent='Beck lesen · Textbelege im Zusammenhang';section.append(h);const note=document.createElement('p');note.textContent='Öffne den vollständigen Auftritt mit Zusammenfassungen, Korrekturhinweisen und dem Druckvergleich von 1826. Deine Untersuchung bleibt geöffnet.';section.append(note);const buttons=document.createElement('div');buttons.className='buttons';for(const [act,scene]of links){const a=document.createElement('a');a.className='linkbutton';a.textContent=act+'. Aufzug · '+scene+'. Auftritt';a.href='../?investigation='+id+'&source='+act+'-'+scene;if(embedded)a.onclick=e=>{e.preventDefault();parent.postMessage({type:'schach-investigation-source',act,scene},location.origin);};buttons.append(a);}section.append(buttons);document.querySelector('#knowledge').append(section);}
const renderOriginalFunction=render;render=()=>{renderOriginalFunction();$('#mission-select').value=state.current;renderSceneLinks();};
render();
