export const eras = [
 {year:'1770',name:'Die Täuschung',person:'Kempelen',eyebrow:'ERSTE PARTIE · MENSCH GEGEN MASCHINE',title:'Ein Zug.\nUnd ein Verdacht.',intro:'Dir gegenüber sitzt ein Automat. Er scheint zu denken. Ziehe eine weisse Figur und beobachte seine Antwort.',question:'Wer hat diesen Zug gemacht?',color:'#c6a778',material:'HOLZ / MESSING'},
 {year:'1798',name:'Die Intrige',person:'Heinrich Beck',eyebrow:'ZWEITE PARTIE · MENSCH ALS MASCHINE',title:'Alle Figuren\nsind beisammen.',intro:'Das Brett wird zur Bühne. Baron Rink spielt gegen sich selbst. Doch wer führt in diesem Haus eigentlich die Züge?',question:'Wer bewegt diese Figur?',color:'#d3a28d',material:'BÜHNE / SAMT'},
 {year:'1980',name:'Die Regel',person:'John Searle',eyebrow:'DRITTE PARTIE · SYNTAX UND SEMANTIK',title:'Richtig gespielt.\nAuch verstanden?',intro:'Du sitzt im chinesischen Zimmer. Du kennst die Zuordnung, aber nicht die Bedeutung. Führe die Anweisung auf dem Brett aus.',question:'Du hast korrekt geantwortet. Hast du verstanden?',color:'#afc9c0',material:'ZEICHEN / PAPIER'},
 {year:'2026',name:'Die Black Box',person:'Künstliche Intelligenz',eyebrow:'VIERTE PARTIE · OUTPUT UND URSACHE',title:'Eine Antwort.\nViele Urheber.',intro:'Kein sichtbarer Gegner. Nur ein schwarzer Kasten. Stelle eine Frage und untersuche, was hinter einer Antwort liegt.',question:'Wer hat diesen Zug gemacht?',color:'#a2bdd8',material:'SILIZIUM / LICHT'}
];
export const characters=[
 {name:'Julie',square:'c3',type:'q',force:'Baron und Baronin · Liebe · eigene Entscheidung',text:'Der Baron sieht Carl als Gatten vor, die Baronin den Grafen. Julie widerspricht: Sie kann zur Entsagung, aber nicht zur Liebe gezwungen werden. Sie lehnt den Schmuck als Mittel der Werbung ab.',reference:'I, 1 und 8; III, 3–4; IV, 10'},
 {name:'Wendheim',square:'f3',type:'n',force:'Liebe · Geldnot · familiäre Abhängigkeit',text:'Wendheim liebt Julie. Der Graf will seine Schulden nutzen, um ihn aus der Stadt zu verdrängen. Wendheim verweigert die Flucht und nimmt eher Arrest in Kauf.',reference:'I, 7; III, 5 und 11'},
 {name:'Carl Ruf',square:'a4',type:'n',force:'Dankbarkeit · Spiellust · eigene Regie',text:'Wendheim hat Carl einst vor Werbern gerettet. Carl hilft ihm und Julie, sucht aber zugleich Aufsehen und übt Druck auf andere aus. Er übernimmt den ersten Kasten und damit selbst die Maschinenrolle.',reference:'I, 7; III, 8; IV, 2 und 8–13'},
 {name:'Sophie',square:'g3',type:'b',force:'Freundschaft · Neugier · eigener Witz',text:'Die Schriftstellerin Sophie widersetzt sich dem Werben für den Grafen. Sie belauscht die Intrige und übermittelt Carl die entscheidenden Nachrichten. Ohne ihre Beobachtung fehlt ihm sein nächster Zug.',reference:'I, 3–4 und 8; III, 5 und 8'},
 {name:'Baron Rink',square:'e1',type:'k',force:'Schachbuch · Heiratsplan · Urteil und Mitgefühl',text:'Rink schaut vor jedem Schachzug ins Buch und zieht beide Seiten. Er lehnt Balken ab, bestimmt aber zunächst Carl als Julies Gatten. Später fragt er Julie selbst und stimmt Wendheim zu.',reference:'I, 1; III, 1; IV, 10'},
 {name:'Baronin',square:'d6',type:'q',force:'Rang und Vermögen · Kontrolle · Intrige',text:'Sie verlangt Julies Heirat mit Balken, plant Wendheims Entfernung und Balkens heimlichen Zutritt. Sophies Beobachtung und Carls Kastenwechsel durchkreuzen ihre Regie.',reference:'III, 3–5 und 8; IV, 6–8'},
 {name:'Graf Balken',square:'e7',type:'p',force:'Rang · Eitelkeit · Geld · Anleitung der Baronin',text:'Balken bietet Schmuck, verweigert Wendheim Hilfe und lässt sich die Intrige erklären. Seine stereotypen Antworten werden hier als Routinen inszeniert. Im zweiten Kasten wird er selbst zum Gegenstand von Carls Spiel.',reference:'II, 4–7; III, 4–5 und 11; IV, 11–13'}
];
export const rules=[{input:'馬',from:'e4',output:'山',to:'c6'},{input:'水',from:'d4',output:'木',to:'f5'},{input:'火',from:'b3',output:'月',to:'e6'}];
export const foundations=['Daten','Menschliche Texte','Bilder','Programmcode','Annotation','Feedback','Training','Mathematische Modelle','Rechenzentren','Energie','Hardware','Inferenz','Output'];
export const questions=['Wissen beide, dass dies ein Springer ist?','Wissen beide, dass der König bedroht sein kann?','Wissen beide, warum dieser Zug stark ist?','Muss man dies wissen?','Reicht es, den richtigen Zug zu machen?'];
