import {createScene} from './scene.js';
import {createRun,stepRun,finishRun,names,evidence,defaults,simulationPage} from './decision-model.js';
import {readingLimit} from './inner-perspectives.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const btn=(p,t,fn)=>{const b=el('button',t);b.type='button';b.onclick=fn;p.append(b);return b;};
export function createDecisionUI({onSource}){
 const dialog=el('dialog',null,'decision-dialog');dialog.setAttribute('aria-label','Entscheidungssimulation Carl und die Träger');document.body.append(dialog);let condition='baseline',mode='counterfactual',runs=[],history=[],revealed=false,verdict='',opener=null,slot=Math.random()<.5,actor='all';let boards=[];
 function board(parent,run,i){if(!boards[i]){const node=el('div',null,'decision-board');node.setAttribute('aria-label','Modellbühne: Carl und beide Träger');parent.append(node);try{const scene=createScene(node,()=>{});scene.setTheme(1);scene.view('top');scene.setZoom(135);boards[i]={node,scene};}catch{node.textContent='3D nicht verfügbar. Zustände und Beziehungen stehen im Protokoll.';boards[i]={node};}}else parent.append(boards[i].node);const scene=boards[i].scene;if(!scene)return;const positions=new Map([['carl','d4'],['first',run.actors.first.cooperates?'c4':'b7'],['second',run.actors.second.cooperates?'e4':'f7']]);scene.setPieces(Object.entries(names).map(([id,label])=>({square:positions.get(id),label,type:id==='carl'?'n':'p',color:id==='carl'?'w':'b'})));const edges=[];for(const id of ['first','second']){if(run.actors[id].cooperates)edges.push({from:id,to:'carl',layer:'position',effect:'release',certainty:'inferred'});if(run.threat)edges.push({from:'carl',to:id,layer:'dependence',effect:'control',certainty:'inferred'});}if(run.counter)edges.push({from:'first',to:'carl',layer:'dependence',effect:'control',certainty:'inferred'});scene.showRelations(edges,positions);scene.speaker(names[run.trace.at(-1)?.actor]);parent.append(el('small','Modellbühne: Nähe = zugesagte Kooperation; rote Pfeile = Druck/Gegenwehr; Blau = aktuell verarbeitende Figur. Keine historischen Bühnenpositionen. Mausrad zoomt, Ziehen dreht.'));}

 const alternatives={baseline:['Textnahe Ausgangslage',{}],identity:['Identitätssignal fehlt',{recognize:false}],money:['Erster Träger lehnt Geld ab',{refuseMoney:true}],payment:['Carl bietet kein Geld an',{payment:0}],counter:['Die Gegendrohung bleibt aus',{counter:false}]};
 function reset(){const settings=alternatives[condition][1];runs=mode==='blind'?(slot?['rules','goals']:['goals','rules']).map(m=>createRun(m,settings)):[createRun('goals'),createRun('goals',settings)];history=[];revealed=false;verdict='';}
 function render(){dialog.replaceChildren();btn(dialog,'Schliessen',()=>dialog.close()).className='strategy-close';dialog.append(el('h2','Carl und die Träger · Entscheidungen untersuchen'),el('p','Eine ausdrücklich konstruierte Simulation zu IV/2. Die Regeln, Bewertungen und Gegenproben sind Interpretationsannahmen. Sie ersetzen weder den Originaltext noch das Innenleben der Figuren. Es läuft kein Sprachmodell.'));
 const toolbar=el('div',null,'decision-controls');const choose=el('select');choose.id='decision-mode';choose.setAttribute('aria-label','Versuchsart');for(const [v,t]of [['counterfactual','Gegenprobe: nur eine Bedingung verändern'],['blind','Blindvergleich: zwei Verfahren']]){const o=el('option',t);o.value=v;choose.append(o);}choose.value=mode;choose.onchange=()=>{mode=choose.value;reset();render();};toolbar.append(choose);
 const change=el('select');change.id='decision-condition';change.setAttribute('aria-label','Veränderte Bedingung');for(const [v,[t]]of Object.entries(alternatives)){const o=el('option',t);o.value=v;change.append(o);}change.value=condition;change.onchange=()=>{condition=change.value;reset();render();};toolbar.append(change);
 btn(toolbar,'Ein Verarbeitungsschritt',()=>{history.push(structuredClone(runs));runs=runs.map(stepRun);render();}).id='decision-step';btn(toolbar,'Bis zum Ergebnis',()=>{history.push(structuredClone(runs));runs=runs.map(finishRun);render();}).id='decision-finish';const back=btn(toolbar,'Schritt zurück',()=>{runs=history.pop();render();});back.disabled=!history.length;btn(toolbar,'Versuch neu beginnen',()=>{reset();render();});toolbar.querySelector('#decision-step').disabled=runs.every(r=>r.ended);toolbar.querySelector('#decision-finish').disabled=runs.every(r=>r.ended);dialog.append(toolbar);
 const filter=el('select');filter.setAttribute('aria-label','Akteur im Ablaufprotokoll');for(const [v,t]of [['all','Alle Akteure'],...Object.entries(names)]){const o=el('option',t);o.value=v;filter.append(o);}filter.value=actor;filter.onchange=()=>{actor=filter.value;render();};dialog.append(filter);
 const grid=el('div',null,'decision-comparison');runs.forEach((run,i)=>{const col=el('section');col.dataset.run=i;col.append(el('h3',mode==='blind'?['Verfahren A','Verfahren B'][i]+(revealed?' · '+(run.model==='rules'?'feste Ablaufregeln':'Ziele und Annahmen'):''):i===0?'Ausgangslage':'Gegenprobe'),el('p',run.outcome||'Noch kein Ergebnis · '+run.trace.length+' Verarbeitungsschritte'));
 if(mode!=='blind'||revealed){board(col,run,i);const last=run.trace.at(-1);if(last)col.append(el('blockquote',evidence[last.evidence].text));for(const [id,state]of Object.entries(run.actors)){if(actor!=='all'&&actor!==id)continue;const card=el('article',null,'decision-actor');card.append(el('h4',names[id]),el('p','Identität: '+state.identity),el('p','Ziel: '+state.goal),el('p','Transportbereitschaft: '+(state.cooperates?'zugesagt':'nicht zugesagt')),el('p','Wahrgenommene Ereignisse: '+state.perceived.filter(e=>e.accessible).map(e=>e.source).join(', ')));col.append(card);}}
 const list=el('ol',null,'decision-trace');for(const t of run.trace.filter(t=>actor==='all'||t.actor===actor)){if(mode==='blind'&&!revealed&&t.phase!=='Handeln')continue;const li=el('li');li.append(el('strong',`${names[t.actor]} · ${mode==='blind'&&!revealed?'Handlung':t.phase}`),el('p',t.detail));if(mode!=='blind'||revealed){if(t.candidates){const table=el('table');for(const c of t.candidates){const tr=el('tr');tr.append(el('td',c.label),el('td',String(c.score)),el('td',c.rule));table.append(tr);}li.append(table);}const d=el('details');d.append(el('summary','Tatsächlicher Zustand vorher / nachher'),el('pre',JSON.stringify({vorher:t.before[t.actor],nachher:t.after[t.actor],welt:t.world},null,2)));li.append(d);btn(li,'Originalbezug',()=>{const e=evidence[t.evidence];onSource(e.page,e.start,e.end);});}list.append(li);}col.append(list);grid.append(col);});dialog.append(grid);
 if(mode==='blind'){const label=el('label','Dein Urteil vor der Offenlegung: Worin unterscheiden sich die Verfahren?'),area=el('textarea');area.id='decision-verdict';area.value=verdict;area.rows=3;area.maxLength=2000;area.disabled=revealed;label.append(area);dialog.append(label);const reveal=btn(dialog,'Verfahren und Protokolle offenlegen',()=>{revealed=true;render();});reveal.id='decision-reveal';reveal.disabled=!runs.every(r=>r.ended)||verdict.trim().length<12;area.oninput=()=>{verdict=area.value;reveal.disabled=!runs.every(r=>r.ended)||verdict.trim().length<12;};dialog.append(el('p','Dies ist ein Vergleich zweier programmierter Verfahren, kein Mensch-Maschine-Turing-Test. Gleiche Ergebnisse können durch unterschiedliche Verfahren entstehen.'));
 }
 dialog.append(el('p','Im Ausgangsmodell folgt Kooperation auf ein Angebot. „Der Unrechte“ wird dadurch nicht „der Rechte“. Prüfe diese Trennung am Original. Zahlenwerte sind gesetzte Gewichte; ihre Offenlegung erlaubt Kritik am Modell.'));
 btn(dialog,'Versuch und Protokolle sichern',()=>{const data=mode==='blind'&&!revealed?{mode,condition,verdict,outputs:runs.map(r=>({outcome:r.outcome,actions:r.trace.filter(t=>t.phase==='Handeln').map(t=>({actor:t.actor,action:t.action}))}))}:{mode,condition,verdict,runs};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='schachmaschine-entscheidungsversuch.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 }
 dialog.addEventListener('close',()=>{boards.forEach(b=>b.scene?.dispose());boards=[];if(opener?.isConnected)opener.focus();});
 return {button(parent,context){const b=btn(parent,'Entscheidungssimulation · Carl und die Träger',()=>{opener=b;reset();dialog.showModal();render();});b.id='decision-open';b.disabled=readingLimit(context.stage,context.state.opened)<simulationPage;b.title=b.disabled?'Wird nach Öffnen von IV. Aufzug, 2. Auftritt freigeschaltet.':'Entscheidungen und Gegenproben schrittweise vergleichen';if(b.disabled)parent.append(el('p','Die Simulation wird bei IV/2 freigeschaltet, damit sie die Handlung nicht vorwegnimmt.'));},hide(){if(dialog.open)dialog.close();}};
}
