import pages from './play-pages.json' with {type:'json'};
export const simulationPage=pages.findIndex(p=>p.id==='text-4-2-0');
export const defaults={recognize:true,counter:true,refuseMoney:false,payment:2};
export const names={carl:'Carl',first:'Erster Träger',second:'Zweiter Träger'};
const source=needle=>{const start=pages[simulationPage].text.indexOf(needle);if(start<0)throw Error(needle);return {page:simulationPage,start,end:start+needle.length,text:needle};};
export const evidence={identity:source('ist das auch der Rechte?'),refusal:source('Sie sind der Unrechte;'),threat:source('zieht ein Zerzerol.'),counter:source('tragen Sie ins Wasser?'),update:source('Diesmal seyd ihr gescheuter als ich.'),payment:source('Hier habt ihr jeder einen Dus katen; wollt ihr mich tragen?'),consent:source('In Gottes Namen.')};
const events=[
 ['identity','first','Identität prüfen'],['refusal','second','Auftrag und Person abgleichen'],['threat','carl','Druck ausüben'],['counter','first','Gegenwehr erwägen'],['update','carl','Erwartung über die Träger prüfen'],['payment','carl','Eine Zahlung anbieten'],['consent','first','Erster Träger entscheidet'],['consent','second','Zweiter Träger entscheidet']
];
const labels={doubt:'Identität bezweifeln',acceptIdentity:'Identität nicht anzweifeln',refuse:'Transport verweigern',wait:'Abwarten',threaten:'Mit der Waffe drohen',counter:'Mit dem Transportweg drohen',yield:'Drohen einstellen',pay:'Zahlung anbieten',withdraw:'Vorhaben abbrechen',carry:'Transport zusagen'};
export function createRun(model='goals',settings={}){return {model,settings:{...defaults,...settings},index:0,phase:0,actors:Object.fromEntries(Object.keys(names).map(id=>[id,{identity:id==='carl'?'Carl kennt seine Identität':'Nicht gesichert',cooperates:false,perceived:[],beliefs:[],goal:id==='carl'?'Transport erreichen':'Entlohnung erhalten und eigene Gefährdung begrenzen'}])),threat:false,counter:false,offer:0,ended:false,outcome:null,trace:[],pending:null};}
function alternatives(run,kind,actor){
 const refusing=run.settings.refuseMoney&&actor==='first';
 const specs={identity:[['doubt',run.settings.recognize?8:0],['acceptIdentity',run.settings.recognize?0:8]],refusal:[['refuse',run.settings.recognize?8:0],['wait',run.settings.recognize?0:8]],threat:[['threaten',6],['pay',3]],counter:[['counter',run.settings.counter?9:0],['wait',run.settings.counter?0:9]],update:[['yield',run.counter?10:3],['threaten',run.counter?-5:6]],payment:[['pay',run.settings.payment>0?8:-2],['withdraw',run.settings.payment>0?1:7]],consent:[['carry',!refusing&&run.offer>0?8:-4],['refuse',refusing||run.offer===0?9:1]]};
 return specs[kind].map(([action,score])=>({action,label:labels[action],score,rule:kind==='consent'?'Zahlung vorhanden und keine ausdrückliche Ablehnung':kind==='update'?'Gegenwehr erhöht die Kosten einer Drohung':kind==='payment'?'Ein verfügbares Angebot eröffnet eine Alternative':'Reaktion auf die wahrgenommene Bedingung'}));
}
export function stepRun(input){const r=structuredClone(input);if(r.ended)return r;const [kind,actor,eventLabel]=events[r.index];const person=r.actors[actor];const entry={step:r.trace.length+1,event:r.index,actor,phase:['Wahrnehmen','Annahmen ändern','Alternativen prüfen','Handeln'][r.phase],before:structuredClone(r.actors),evidence:kind};
 if(r.phase===0){const accessible=kind!=='identity'||r.settings.recognize;person.perceived.push({kind,accessible,source:kind,counterfactual:!accessible});r.pending={kind,actor,accessible,eventLabel};entry.detail=accessible?eventLabel+' · Textbezug: '+evidence[kind].text:'Gegenprobe: Das Identitätssignal wird diesem Modell nicht bereitgestellt.';}
 if(r.phase===1){if(kind==='identity'||kind==='refusal'){person.identity=r.settings.recognize?'Vermutung: nicht der bestellte Graf':'Identität weiterhin nicht gesichert';}if(kind==='update'){person.beliefs.push({claim:r.counter?'Träger können den Transport gegen Carl wenden':'Keine Gegenwehr beobachtet',status:r.counter?'beobachtet':'fehlender Beleg',source:kind});}entry.detail=kind==='identity'||kind==='refusal'?person.identity:kind==='update'?person.beliefs.at(-1).claim:'Keine neue Identitätsinformation. Ziele und Identitätsannahmen bleiben getrennt.';}
 if(r.phase===2){r.pending.candidates=alternatives(r,kind,actor);const scripted={identity:'doubt',refusal:'refuse',threat:'threaten',counter:'counter',update:'yield',payment:'pay',consent:'carry'};r.pending.selected=r.model==='rules'?scripted[kind]:r.pending.candidates.reduce((a,b)=>a.score>=b.score?a:b).action;entry.candidates=structuredClone(r.pending.candidates);entry.detail=r.model==='rules'?'Feste Regel: An dieser Ablaufposition wähle '+labels[r.pending.selected]+'. Bewertungen werden nicht verwendet.':'Zielmodell: Wähle die höchste Bewertung. Zahlen sind gesetzte Modellannahmen, keine psychologischen Messwerte.';}
 if(r.phase===3){const action=r.pending.selected;entry.action=action;entry.detail=labels[action];if(action==='threaten')r.threat=true;if(action==='counter'){r.counter=r.settings.counter;if(!r.counter)entry.detail+=' · Ausführung blockiert: In dieser Gegenprobe ist keine Gegenwehr möglich.';}if(action==='yield')r.threat=false;if(action==='pay')r.offer=r.settings.payment;if(action==='withdraw'){r.ended=true;r.outcome='Carl bricht den Transportversuch ab.';}if(kind==='consent'){const allowed=r.offer>0&&!(actor==='first'&&r.settings.refuseMoney);person.cooperates=action==='carry'&&allowed;if(action==='carry'&&!allowed)entry.detail+=' · Ausführung blockiert: Die Versuchsanordnung erlaubt hier keine Kooperation.';}
  // Payment never rewrites identity. Actual action depends on an actor's own acceptance.
  for(const target of Object.values(r.actors))target.perceived.push({kind:'action',actor,action,offer:r.offer,source:kind,accessible:true});r.index++;r.pending=null;if(r.index===events.length){r.ended=true;r.outcome=r.actors.first.cooperates&&r.actors.second.cooperates?'Beide tragen Carl. Identitätszweifel sind dadurch nicht widerlegt.':'Der gemeinsame Transport kommt nicht zustande.';}}
 entry.after=structuredClone(r.actors);entry.world={offer:r.offer,threat:r.threat,counter:r.counter};r.trace.push(entry);r.phase=(r.phase+1)%4;return r;}
export function finishRun(run){let r=run;while(!r.ended)r=stepRun(r);return r;}
export function agentContext(run,actor){if(!names[actor])throw Error('Unbekannte Figur');const state=structuredClone(run.actors[actor]);const ids=[...new Set(state.perceived.filter(x=>x.accessible).map(x=>x.source))];return {role:actor,state,evidence:ids.map(id=>({id,...evidence[id]})),allowedActions:run.pending?.actor===actor?run.pending.candidates?.map(x=>x.action)||[]:[]};}
export function validateProposal(value,context){if(!value||!context.allowedActions.includes(value.action))return 'Handlung ist in diesem Zustand nicht zulässig.';if(!Array.isArray(value.evidenceIds)||!value.evidenceIds.length||value.evidenceIds.some(id=>!context.evidence.some(e=>e.id===id)))return 'Beleg fehlt oder gehört nicht zum Informationszugang dieser Figur.';return '';}
