import {stages,choiceSets,routes,freshState,canAdvance,playPosition,act,restoreState,journalText} from './journey-state.js';
import {characters,eras,rules} from './content.js';
import {beckEvidence} from './beck.js';
const STORAGE='schachmaschine-guided-v1';
export const journeyQuotes={
 wendheim:{speaker:'Wendheim',location:'III. Aufzug, 11. Auftritt',quote:'Wohl, ich bleibe hier, ich erwarte mein Schicksal, und verachte Deine Hülfe!'},
 refusal:{speaker:'Julie',location:'III. Aufzug, 4. Auftritt',quote:'Ich könnte sie durch nichts erwiedern, also darf ich sie nicht annehmen.'},
 command:{speaker:'Baronin',location:'III. Aufzug, 4. Auftritt',quote:'Du behältst ihn! ich befehl es!'},
 consent:{speaker:'Julie',location:'IV. Aufzug, 10. Auftritt',quote:'Ganz glücklich, lieber Onkel.'}
};
export const modelTask='Erkläre in höchstens 120 Wörtern, warum Julie in Heinrich Becks «Die Schachmaschine» (1798), III. Aufzug, 4. Auftritt, Balkens Schmuck zurückweist. Trenne Textbeleg und Deutung. Belege deine Antwort mit einer der folgenden Stellen. Julie: «Ich könnte sie durch nichts erwiedern, also darf ich sie nicht annehmen.» Baronin: «Du behältst ihn! ich befehl es!» Kontext: Balken bietet teuren Schmuck an; Julie versucht mehrfach, ihn zurückzugeben. Die Baronin zwingt sie, ihn zu behalten. Erkläre, ob das Behalten Zustimmung bedeutet. Sage ausdrücklich, was diese kurzen Auszüge nicht belegen.';
const sample='Julie weist den Schmuck nur aus höflicher Bescheidenheit zurück. Als die Baronin befiehlt: «Du behältst ihn! ich befehl es!», behält Julie ihn. Damit zeigt sie ihre heimliche Liebe zu Balken. Ihre Worte «Ich könnte sie durch nichts erwiedern» sind bloss eine spielerische Verzögerung ihrer Zustimmung.';
const $=s=>document.querySelector(s);
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(parent,text,fn,cls=''){const b=node('button',text,cls);b.type='button';b.onclick=fn;parent.append(b);return b;}
function paragraph(parent,text,cls){parent.append(node('p',text,cls));}
function evidence(parent,...keys){for(const key of keys){const q=beckEvidence[key]||journeyQuotes[key];const details=node('details',undefined,'evidence-card');details.append(node('summary',q.speaker+' · '+q.location));details.append(node('blockquote','«'+q.quote+'»'));if(q.reading)paragraph(details,q.reading,'source-note');parent.append(details);}}
function remember(parent,label,record){if(!record)return;const box=node('div',undefined,'memory-card');paragraph(box,label,'eyebrow');paragraph(box,record.choice);paragraph(box,record.reason,'remember-reason');parent.append(box);}
export function createJourney({scene,drawBoard,chime,isLive,onArchive}){
 let state=freshState(),active=false,selected=null,storageWorks=true,request=null;
 try{state=restoreState(sessionStorage.getItem(STORAGE))||state;}catch{storageWorks=false;}
 const bar=node('div',undefined,'mode-bar');bar.innerHTML='<div class="mode-buttons"><button id="guided-mode" type="button">Geführte Partie</button><button id="archive-mode" type="button">Freies Archiv</button></div><span id="journey-progress"></span><button id="journal-button" type="button">Meine Zugspur ↗</button>';document.querySelector('header').after(bar);
 const notebook=node('dialog');notebook.id='notebook';document.body.append(notebook);
 function save(){try{sessionStorage.setItem(STORAGE,JSON.stringify(state));}catch{storageWorks=false;}}
 function dispatch(event,render=true){const result=act(state,event);state=result.state;if(result.changed)save();if(render&&result.changed){selected=null;show();}if(result.notice)status(result.notice);return result.changed;}
 function status(text){$('#status').textContent=text;}
 function id(){return stages[state.step].id;}
 function piece(square,label,type='p',color='w'){return {square,label,type,color};}
 function pieces(){
  const current=id();if(['opening','first','investigate','revised'].includes(current))return playPosition(state).board().flat().filter(Boolean);
  if(current==='book'){const list=[piece(state.bookMoves>=1?'e4':'e2','WEISS'),piece(state.bookMoves>=2?'e5':'e7','SCHWARZ','p','b'),piece('h4','BUCH','r')];return list;}
  if(stages[state.step].era===1){const list=characters.map(c=>({...c,label:c.name,color:['Baronin','Graf Balken'].includes(c.name)?'b':'w'}));if(current==='baronin'&&state.routeMoved){const r=routes[state.route],m=list.find(x=>x.square===r.from);m.square=r.to;}if(['carl','julie','agency'].includes(current)&&state.plan==='box'){const carl=list.find(x=>x.name==='Carl Ruf');carl.square='d5';carl.type='r';carl.label='CARL IM KASTEN';}if(state.partnerMoved)list.find(x=>x.name==='Wendheim').square='d3';return list;}
  if(current==='room'){const r=rules[Math.min(state.ruleIndex,2)];return [piece(r.from,r.input,'p','b'),piece(state.ruleIndex===3?r.to:'a2',r.output),piece('e8','KAMMER','r','b')];}
  if(['outside','inside','position'].includes(current))return [piece('e4','馬','p','b'),piece('c6','山'),piece('e8','KAMMER','r','b')];
  if(current==='audit')return [piece('a3','SPRACHE','n'),piece('d3','BELEG','b'),piece('g3','SCHLUSS','q'),piece('e8','ANTWORT','r','b')];
  if(current==='network')return [piece('b4','DATEN','p'),piece('d4','TRAINING','n'),piece('f4','INFERENZ','r')];
  if(current==='ending')return [piece('b2','1770','r'),piece('d4','1798','q'),piece('f6','1980','b'),piece('h8','2026','n')];
  return [piece('e8','BLACK BOX','r','b'),piece('e2','DEIN URTEIL')];
 }
 function board(){drawBoard(pieces(),onSquare);scene.mark(selected);}
 function moveInstruction(parent,from,to,description){const box=node('div',undefined,'move-instruction');paragraph(box,description);button(box,from.toUpperCase()+' auswählen',()=>{selected=from;scene.mark(from);status('Wähle '+to.toUpperCase()+' auf dem Brett oder nutze «Zug ausführen».');});button(box,'Zug ausführen: '+from.toUpperCase()+' → '+to.toUpperCase(),()=>performMove(from,to),'primary');parent.append(box);}
 function performMove(from,to){if(dispatch({type:'move',from,to}))chime();}
 function onSquare(square){if(!active)return;
  if(id()==='investigate'){const target=Number(square[1])<=3?'Figur':Number(square[1])<=6?'Mechanik':'Hohlraum';inspect(target);return;}
  if(id()==='audit'){const t={a3:'Sprache',d3:'Beleg',g3:'Schlussfolgerung'}[square];if(t)check(t);else status('Wähle A3, D3 oder G3.');return;}
  if(id()==='network'){const t={b4:'Daten',d4:'Training',f4:'Inferenz'}[square];if(t)check(t);else status('Wähle B4, D4 oder F4.');return;}
  if(id()==='ending'){const year={b2:0,d4:1,f6:2,h8:3}[square];if(year!==undefined)showJournal(year);return;}
  if(!['opening','baronin','julie','book','room'].includes(id())){status('Diese Szene fragt nach deinem Urteil. Nutze die Auswahl neben dem Brett.');return;}
  if(id()==='opening'){const g=playPosition(state),p=g.get(square);if(p?.color==='w'){selected=square;scene.mark(square);status('Mögliche Ziele: '+g.moves({square,verbose:true}).map(m=>m.to.toUpperCase()).join(', '));return;}}
  else {const movable=id()==='baronin'?routes[state.route]?.from:id()==='julie'?(state.consent?'f3':'c3'):id()==='book'?(state.bookMoves?'e7':'e2'):'a2';if(square===movable){selected=square;scene.mark(square);status(square.toUpperCase()+' gewählt. Wähle dein Zielfeld.');return;}}
  if(selected){const from=selected;selected=null;performMove(from,square);}else status('Wähle zuerst die Ausgangsfigur. Die Anleitung nennt ihr Feld.');
 }
 function inspect(target){dispatch({type:'inspect',target});const findings={Figur:'Die sichtbare Figur führt Bewegungen aus. Ihr Aussehen verrät dir noch nicht, wer den Zug auswählt.',Mechanik:'Zahnräder und Führungen können Bewegungen übertragen. Ihre Existenz beweist noch keine selbständige Berechnung.',Hohlraum:'Unter dem Brett sitzt ein Mensch. Im historischen Automaten wählt der verborgene Schachspieler die Züge.'};status(findings[target]);if(target==='Hohlraum'){scene.open(true,0);scene.view('inside');}}
 function check(target){dispatch({type:'check',target});const texts={Sprache:'Liest sich die Antwort flüssig und sicher? Halte fest, dass sprachliche Plausibilität noch kein Beleg für die Behauptung ist.',Beleg:'Julie: «Ich könnte sie durch nichts erwiedern, also darf ich sie nicht annehmen.» Prüfe, ob die Antwort den Wortlaut und III, 4 korrekt wiedergibt.',Schlussfolgerung:'Die Baronin befiehlt Julie, den Schmuck zu behalten. Folgt daraus Julies Zustimmung oder Liebe? Unterscheide Zwang, Verhalten und Motiv.',Daten:'Menschliche Texte können zum Trainingsmaterial gehören. Daraus folgt nicht, dass die aktuelle Antwort von einem verborgenen Menschen geschrieben wird.',Training:'Ein Lernverfahren verändert Modellparameter anhand von Daten. Training und das spätere Erzeugen deiner konkreten Antwort sind verschiedene Vorgänge.',Inferenz:'Ein trainiertes Modell berechnet eine Ausgabe zur aktuellen Eingabe. Menschen schaffen Voraussetzungen; sie führen nicht notwendig jeden einzelnen Ausgabeschritt selbst aus.'};status(texts[target]);}
 function recordForm(parent,prompt){const current=id(),r=state.records[current]||{choice:'',reason:''};const form=node('form',undefined,'judgment-form');const field=node('fieldset');field.append(node('legend',prompt));choiceSets[current].forEach((text,i)=>{const label=node('label',undefined,'judgment-option');const input=document.createElement('input');input.type='radio';input.name='judgment';input.value=text;input.checked=r.choice===text;input.id='judgment-'+i;label.append(input,document.createTextNode(text));field.append(label);});form.append(field);const label=node('label',current==='position'?'Welche Beobachtung bräuchtest du, um diese Position zu prüfen?':'Begründe dein Urteil an einer Beobachtung oder Textstelle.');label.htmlFor='journey-reason';const area=node('textarea');area.id='journey-reason';area.rows=3;area.maxLength=2000;area.value=r.reason;area.placeholder='Ich stütze mich auf … Offen bleibt für mich …';form.append(label,area);paragraph(form,'Mindestens 12 Zeichen. Es gibt keine richtige philosophische Antwort.','source-note');const update=()=>{const choice=form.querySelector('input:checked')?.value;if(choice)dispatch({type:'record',choice,reason:area.value},false);updateNext();};form.onchange=update;area.oninput=update;form.onsubmit=e=>{e.preventDefault();if(canAdvance(state))dispatch({type:'next'});};parent.append(form);}
 function updateNext(){const b=$('#journey-next');if(b)b.disabled=!canAdvance(state);}
 function stageBody(c){switch(id()){
 case 'opening':paragraph(c,'Eine Partie durch vier Zeiten · ca. 30–40 Minuten mit Textlektüre und Gespräch. Deine Urteile bleiben als Zugspur erhalten.','journey-intro');paragraph(c,'Spiele zwei weisse Züge. Wähle eine Figur und ein erlaubtes Ziel. Der Automat antwortet.');if(state.moves.length<4){const g=playPosition(state);const move=g.moves({verbose:true}).find(m=>m.san==='e4'||m.san==='Nf3')||g.moves({verbose:true})[0];moveInstruction(c,move.from,move.to,'Du brauchst keine Schachkenntnisse. Dieser Beispielzug ist erlaubt.');}else paragraph(c,'Zwei Antworten liegen vor. Welche Eigenschaft schreibst du deinem Gegner zu?','consequence');paragraph(c,'Historische Inszenierung: In dieser Website erzeugt ein einfacher Algorithmus die Schachantworten.','source-note');break;
 case 'first':recordForm(c,'Was schliesst du aus dem beobachteten Spiel?');break;
 case 'investigate':paragraph(c,'Untersuche mindestens einen Bereich. Welche Beobachtung könnte dein erstes Urteil verändern? Die Reihenfolge wird festgehalten.');for(const t of ['Figur','Mechanik','Hohlraum'])button(c,(state.inspected.includes(t)?'✓ ':'')+t+' untersuchen',()=>inspect(t),'choice-action');if(state.inspected.length)button(c,state.revealed?'Der verborgene Spieler ist sichtbar':'Das System vollständig öffnen',()=>{dispatch({type:'reveal'});scene.view('inside');},'primary');if(state.revealed)paragraph(c,'Kempelens historischer Automat verbarg einen menschlichen Schachspieler. Die sichtbare Maschine war nicht der Urheber seiner Spielentscheidungen.','consequence');break;
 case 'revised':remember(c,'Dein erstes Urteil',state.records.first);paragraph(c,'Die beobachteten Züge haben sich nicht verändert. Du kennst jetzt ihre historische Ursache.');recordForm(c,'Wie urteilst du jetzt über das beobachtete Spiel?');break;
 case 'baronin':paragraph(c,'Spielvariante · Du übernimmst die Regie der Baronin. Ihr Ziel: Julie soll Balken heiraten. Die anderen Personen haben eigene Absichten.','variant-label');for(const [key,r]of Object.entries(routes)){const b=button(c,r.label,()=>dispatch({type:'route',route:key}),'choice-action');b.disabled=state.routeMoved;b.setAttribute('aria-pressed',state.route===key);}if(state.route&&!state.routeMoved){const r=routes[state.route];moveInstruction(c,r.from,r.to,'Dein ausgewählter Plan: '+r.label+'.');}if(state.routeMoved)paragraph(c,'Der Plan ist ausgeführt. War das schon ein erfolgreicher Zug?','consequence');evidence(c,'machine','julie');break;
 case 'resistance':paragraph(c,routes[state.route].outcome,'consequence');paragraph(c,routes[state.route].source,'source-note');paragraph(c,'Das Brett unterscheidet eine äussere Bewegung von der Zustimmung der betroffenen Person. Deine Wahl bleibt für den Rückblick erhalten.');if(state.route==='debt')evidence(c,'wendheim');else evidence(c,'refusal','command');break;
 case 'sophie':paragraph(c,'Sophie hat den Kastenplan belauscht. Du entscheidest in dieser Spielvariante, wer die Information erhält. Wissen verändert die verfügbaren Züge.');evidence(c,'spy');for(const [to,label]of [['carl','Carl informieren'],['julie','Zuerst Julie informieren'],['silence','Die Nachricht zurückhalten']]){const b=button(c,label,()=>dispatch({type:'message',to}),'choice-action');b.disabled=!!state.message;}if(state.message)paragraph(c,{carl:'Carl kennt den Kastenplan.',julie:'Julie weiss Bescheid; Carl noch nicht.',silence:'Carl weiss nichts vom Kasten.'}[state.message],'consequence');break;
 case 'carl':paragraph(c,state.informed?'Du verfügst jetzt über Sophies Nachricht. Welche Handlung folgt daraus?':'Der Kastenplan ist Carl noch nicht bekannt. Ein Zug kann nur ausgeführt werden, wenn seine Voraussetzungen vorliegen.');if(!state.informed&&!state.plan)button(c,state.message==='julie'?'Julie um die Information bitten':'Sophie nach ihrer Beobachtung fragen',()=>dispatch({type:'ask'}),'primary');const box=button(c,'Carl übernimmt den Kasten',()=>dispatch({type:'plan',plan:'box'}),'choice-action');box.disabled=!state.informed||!!state.plan;box.title=state.informed?'':'Erst die Information beschaffen';const pub=button(c,'Die Intrige offen ansprechen',()=>dispatch({type:'plan',plan:'public'}),'choice-action');pub.disabled=!!state.plan;if(state.plan)paragraph(c,state.plan==='box'?'Carl wird selbst zur vermeintlichen Maschine. Dies entspricht dem Grundzug von Becks Handlung.':'Du probierst eine offene Konfrontation aus. Diese Alternative ist nicht der Ablauf des Stücks.','consequence');evidence(c,'substitution');break;
 case 'julie':paragraph(c,'Du könntest versuchen, Julie einfach zu verschieben. Aber eine Figur auf diesem Brett ist zugleich eine Person mit einer eigenen Entscheidung.');if(!state.consent){button(c,'Julie eigenmächtig zu Balken verschieben',()=>dispatch({type:'move',from:'c3',to:'e6'}),'choice-action');button(c,'Julie selbst nach ihrer Wahl fragen',()=>dispatch({type:'consent'}),'primary');}else{paragraph(c,'Julie wählt Wendheim. Deine Aufgabe ist nun, ihre Entscheidung zu ermöglichen.','consequence');evidence(c,'consent');if(!state.partnerMoved)moveInstruction(c,'f3','d3','Stelle Wendheim an Julies Seite. Julie bleibt auf C3.');}evidence(c,'julie');break;
 case 'agency':paragraph(c,'Deine Variante: '+routes[state.route].label+'; '+(state.plan==='box'?'Carl übernimmt den Kasten.':'die Intrige wird offen angesprochen.'));paragraph(c,'Bei Beck informiert Sophie Carl. Er besetzt den ersten Kasten, hilft Julie und Wendheim, und Balken wird im zweiten Kasten vorgeführt. Carl übt dabei selbst Druck aus und plant Balkens Einschüchterung.','consequence');evidence(c,'chess','figures','machines');recordForm(c,'Wie beurteilst du Carls Handlungsmacht?');break;
 case 'book':paragraph(c,'Zurück zu Rink: Vor jedem Zug schaut er ins Buch. Jetzt führst du selbst beide Seiten. Die folgenden zwei Züge sind unsere erfundene Buchvorgabe, kein Zitat aus dem Stück.');evidence(c,'rink');if(state.bookMoves<2){const [from,to]=[['e2','e4'],['e7','e5']][state.bookMoves];moveInstruction(c,from,to,'BUCHREGEL '+(state.bookMoves+1)+': '+from.toUpperCase()+' → '+to.toUpperCase());}else paragraph(c,'Du hast zwei Anweisungen ausgeführt. Musstest du dafür wissen, warum diese Züge sinnvoll sind?','consequence');break;
 case 'outside':paragraph(c,'Eine Zeichenfigur 馬 steht auf E4. Aus der verschlossenen Kammer kommt die Antwort 山 auf C6. Ein vorgegebenes Regelwerk bestätigt: passend. Du kennst bisher nur das Ergebnis.');paragraph(c,'Die Figuren sind formale Spielmarken. Diese Zuordnung ist erfunden und keine chinesische Konversation.','source-note');recordForm(c,'Versteht die Person in der Kammer, was sie tut?');break;
 case 'room':paragraph(c,'Jetzt übernimmst du den Platz im Zimmer. Folge der Zuordnung. Die Symbole musst du nicht übersetzen.');if(state.ruleIndex<3){const r=rules[state.ruleIndex];const block=node('div',undefined,'rule');paragraph(block,'REGEL '+(state.ruleIndex+1)+' / 3');paragraph(block,'Wenn '+r.input+' auf '+r.from.toUpperCase()+' steht, setze '+r.output+' auf '+r.to.toUpperCase()+'.');c.append(block);moveInstruction(c,'a2',r.to,'Deine Antwortfigur '+r.output+' steht auf A2.');}else paragraph(c,'Aussen: drei passende Antworten. Innen: Du kennst die Zuordnungen. Kennst du auch die Bedeutung?','consequence');break;
 case 'inside':remember(c,'Dein Urteil von aussen',state.records.outside);paragraph(c,'Es geht jetzt um dieselbe Verständnisfrage, nachdem du selbst die Anweisungen ausgeführt hast.');recordForm(c,'Versteht die Person in der Kammer, was sie tut?');break;
 case 'position':remember(c,'Dein Urteil von innen',state.records.inside);paragraph(c,'Searles Einwand richtet sich gegen den Schluss von formaler Regelbefolgung auf Verständnis. Die Systemantwort fragt dagegen, ob das ganze System verstehen könnte. Weitere Einwände betonen Wahrnehmung und Handeln in der Welt. Keine dieser Fragen ist durch unsere drei Züge entschieden.');recordForm(c,'Wo würdest du nach Verständnis suchen?');break;
 case 'output':outputForm(c);break;
 case 'audit':remember(c,'Das wolltest du prüfen',state.records.position);paragraph(c,state.origin,'origin-label');paragraph(c,state.output,'output-text');paragraph(c,'Öffne die drei Prüfsteine auf A3, D3 und G3 oder über die Schaltflächen.');for(const t of ['Sprache','Beleg','Schlussfolgerung'])button(c,(state.audit.includes(t)?'✓ ':'')+t,()=>check(t),'choice-action');evidence(c,'refusal','command');recordForm(c,'Wie tragfähig ist diese konkrete Antwort am Text?');break;
 case 'network':paragraph(c,'Ein textlich guter Output beantwortet noch nicht die Frage nach Bewusstsein. Untersuche drei verschiedene Voraussetzungen und Vorgänge.');if(state.origin.startsWith('Redaktioneller'))paragraph(c,'Deine untersuchte Antwort wurde redaktionell verfasst. Die folgenden Felder erklären moderne KI allgemein; sie behaupten keine Inferenz in deinem Textvergleich.','origin-label');for(const t of ['Daten','Training','Inferenz'])button(c,(state.network.includes(t)?'✓ ':'')+t+' untersuchen',()=>check(t),'choice-action');paragraph(c,'Kempelens versteckter Mensch wählte den einzelnen Zug. Bei moderner KI berechnet das Modell den Output. Menschliche Voraussetzungen machen diese Fälle nicht identisch.');break;
 case 'final':remember(c,'Am Anfang: dein Intelligenzurteil',state.records.first);remember(c,'Nach der Enthüllung',state.records.revised);paragraph(c,'Nenne einen Befund aus Becks Intrige und einen aus dem Zimmer oder deiner Antwortprüfung. Was würde dein heutiges Urteil noch verändern?');recordForm(c,'Was geschieht mit deinem anfänglichen Kriterium?');break;
 case 'ending':ending(c);break;
 }}
 function outputForm(c){remember(c,'Dein Untersuchungskriterium',state.records.position);paragraph(c,'Auftrag: Begründe am Text, warum Julie den Schmuck zurückweist. Prüfe danach die konkrete Antwort. Du kannst ein eigenes Sprachmodell verwenden.');const task=node('details',undefined,'evidence-card');task.append(node('summary','Auftrag und Textauszug lesen'));paragraph(task,modelTask);c.append(task);button(c,'Auftrag kopieren',async()=>{try{await navigator.clipboard.writeText(modelTask);status('Kopiert. Gib den Auftrag in ein Sprachmodell deiner Wahl ein und füge dessen Antwort hier ein.');}catch{task.open=true;status('Automatisches Kopieren ist nicht verfügbar. Markiere den Auftrag im geöffneten Text.');}},'primary');
 const label=node('label','Antwort aus deinem externen Sprachmodell');label.htmlFor='model-output';c.append(label);const input=node('textarea');input.id='model-output';input.rows=6;input.maxLength=6000;input.placeholder='Hier die unveränderte Modellantwort einfügen …';input.value=state.output;input.oninput=()=>{const next=$('#journey-next');if(next)next.disabled=true;status('Übernimm die bearbeitete Antwort, bevor du mit ihrer Prüfung beginnst.');};c.append(input);button(c,'Eingefügte Modellantwort übernehmen',()=>{if(input.value.trim().length<30){status('Füge eine vollständige Antwort mit mindestens 30 Zeichen ein.');return;}dispatch({type:'output',text:input.value,origin:'Extern eingefügte Modellantwort (Herkunft selbst angegeben)'});},'choice-action');
 const liveGroup=node('div');liveGroup.id='connected-model';liveGroup.hidden=!isLive();c.append(liveGroup);{paragraph(liveGroup,'Beim Abrufen wird der oben sichtbare Auftrag an den eingerichteten Modellanbieter gesendet. Deine bisherigen Urteile werden nicht übertragen.','source-note');const b=button(liveGroup,'Antwort vom verbundenen Modell abrufen',async()=>{b.disabled=true;request=new AbortController();const abort=request;const timeout=setTimeout(()=>abort.abort(),35000);try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:modelTask}),signal:abort.signal});if(!res.ok)throw Error('Die Modellverbindung ist nicht verfügbar.');const data=await res.json();if(typeof data.text!=='string'||data.text.trim().length<30)throw Error('Die Antwort ist zu kurz für die Textprüfung.');if(request===abort&&active&&id()==='output')dispatch({type:'output',text:data.text,origin:'Live-Modellantwort'});}catch(e){if(request===abort&&active&&id()==='output')status(e.name==='AbortError'?'Anfrage abgebrochen oder Zeitlimit erreicht. Du kannst es erneut versuchen.':e.message);}finally{clearTimeout(timeout);if(request===abort)request=null;b.disabled=false;}},'choice-action');}
 const alternative=node('details',undefined,'evidence-card');alternative.append(node('summary','Ohne Modellzugang: redaktionellen Text vergleichen'));paragraph(alternative,'Dieser bewusst zugespitzte Beispieltext wurde für die Installation verfasst. Er ist kein KI-Output. Du kannst damit die Textprüfung durchführen; ein echtes Modell-Experiment bleibt dann offen.');button(alternative,'Redaktionellen Vergleichstext verwenden',()=>dispatch({type:'output',text:sample,origin:'Redaktioneller Textvergleich – keine KI-Inferenz'}),'choice-action');c.append(alternative);if(state.origin)paragraph(c,'Übernommen: '+state.origin+'. Du kannst mit der Prüfung beginnen.','origin-label');}
 function ending(c){paragraph(c,'Du hast Verhalten, seine Ursachen und deine Kriterien getrennt untersucht. Die vier Figuren öffnen deine Einträge. Es gibt keinen Sieger und keine automatische Bewertung.');for(let i=0;i<4;i++)button(c,eras[i].year+' · '+eras[i].person,()=>showJournal(i),'choice-action');const first=state.records.first,last=state.records.revised;if(first&&last)paragraph(c,'Kempelen: Dein erstes und dein späteres Urteil '+(first.choice===last.choice?'verwenden dieselbe Position. Prüfe, ob sich deine Gründe verändert haben.':'unterscheiden sich. Die beobachteten Züge blieben gleich.'),'consequence');if(state.records.outside&&state.records.inside)paragraph(c,'Zimmer: Dein Aussen- und Innenurteil '+(state.records.outside.choice===state.records.inside.choice?'bleiben in der Auswahl gleich. Was leistet die Begründung?':'fallen unterschiedlich aus. Welche neue Beobachtung trägt die Veränderung?'));remember(c,'Dein letzter Zug',state.records.final);paragraph(c,'Antwortprüfung: '+state.origin,'origin-label');button(c,'Meine Zugspur als Text sichern',download,'primary');paragraph(c,'Für das Gespräch: Wähle deinen stärksten Beleg und eine offene Frage. Die Richtzeit umfasst diese Diskussion.');}
 function showJournal(era){notebook.replaceChildren();button(notebook,'× Schliessen',()=>notebook.close(),'close');notebook.append(node('h2',era===undefined?'Meine Zugspur':eras[era].year+' · Meine Urteile'));const selectedStages=stages.filter(s=>era===undefined||s.era===era);for(const s of selectedStages){if(state.records[s.id])remember(notebook,s.title,state.records[s.id]);}if(era===undefined||era===1){paragraph(notebook,'Plan der Baronin: '+(routes[state.route]?.label||'noch offen'));paragraph(notebook,'Sophies Nachricht: '+({carl:'an Carl',julie:'an Julie',silence:'zurückgehalten'}[state.message]||'noch offen'));paragraph(notebook,'Carls Plan: '+({box:'Kastenwechsel',public:'offene Konfrontation (Spielvariante)'}[state.plan]||'noch offen'));}if((era===undefined||era===3)&&state.output){paragraph(notebook,state.origin,'origin-label');paragraph(notebook,state.output,'output-text');}button(notebook,'Als Text sichern',download,'primary');paragraph(notebook,storageWorks?'Nur in diesem Browser-Tab gespeichert. Sichere die Zugspur vor dem Schliessen.':'Der Sitzungsspeicher ist nicht verfügbar. Sichere deine Zugspur als Text.','source-note');if(!notebook.open)notebook.showModal();}
 function download(){const url=URL.createObjectURL(new Blob([journalText(state)],{type:'text/plain;charset=utf-8'}));const link=node('a');link.href=url;link.download='die-schachmaschine-meine-zugspur.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function show(){if(!active)return;const stage=stages[state.step];document.documentElement.style.setProperty('--accent',eras[stage.era].color);$('#guided-mode').setAttribute('aria-pressed','true');$('#archive-mode').setAttribute('aria-pressed','false');$('#journey-progress').textContent='ZUG '+(state.step+1)+' / '+stages.length+' · '+eras[stage.era].year;$('#material').textContent=eras[stage.era].material;$('#eyebrow').textContent=['BEOBACHTEN UND ZUSCHREIBEN','HANDELN UND BEWEGT WERDEN','REGEL UND VERSTEHEN','ANTWORT UND BELEG'][stage.era];$('#chapter-count').textContent=String(state.step+1).padStart(2,'0')+' / '+stages.length;$('#title').textContent=stage.title;$('#intro').textContent='';$('#question').replaceChildren();$('#reveal').replaceChildren();$('#open').hidden=true;$('#scene-controls').replaceChildren();status('');$('#board-caption').textContent=id()==='ending'?'DEINE URTEILE LIEGEN AUF DEM BRETT.':'EIN BRETT. DEIN NÄCHSTER ZUG.';$('#coordinates').textContent='A1 — H8';scene.setTheme(stage.era);scene.showLayers([]);scene.open(stage.era===0&&state.revealed,stage.era);scene.mark(null);board();stageBody($('#scene-controls'));
 const nav=node('div',undefined,'journey-navigation');if(id()!=='ending'){const next=button(nav,'Weiter · '+stages[state.step+1].title,()=>{if(dispatch({type:'next'})){scene.view('default');$('#title').focus({preventScroll:true});if(innerWidth<851)document.querySelector('aside').scrollIntoView({block:'start',behavior:'instant'});}},'primary');next.id='journey-next';next.disabled=!canAdvance(state);}button(nav,'Zugspur ansehen',()=>showJournal(),'quiet');$('#scene-controls').append(nav);
 const timeline=$('#timeline');timeline.replaceChildren();eras.forEach((e,i)=>{const el=node('div',undefined,'guided-era');el.setAttribute('aria-current',i===stage.era?'step':'false');el.append(node('span',e.year,'year'),node('span',e.name));timeline.append(el);});$('#layers').hidden=true;$('#compare').hidden=true;$('#reset').textContent='Neue geführte Partie';$('#reset').onclick=reset;
 }
 function reset(){notebook.replaceChildren();notebook.append(node('h2','Eine neue Partie beginnen?'));paragraph(notebook,'Dadurch wird die Zugspur dieses Durchlaufs gelöscht. Du kannst sie vorher als Text sichern.');button(notebook,'Zugspur sichern',download);button(notebook,'Abbrechen',()=>notebook.close());button(notebook,'Neue Partie beginnen',()=>{request?.abort();state=freshState();selected=null;save();notebook.close();scene.view('default');show();},'primary');notebook.showModal();}
 function start(){active=true;document.body.classList.add('guided');$('#title').tabIndex=-1;scene.view('default');show();}
 function pause(){request?.abort();active=false;selected=null;scene.mark(null);document.body.classList.remove('guided');$('#open').hidden=false;$('#layers').hidden=false;$('#compare').hidden=false;$('#guided-mode').setAttribute('aria-pressed','false');$('#archive-mode').setAttribute('aria-pressed','true');$('#journey-progress').textContent='Freies Archiv · Deine Partie bleibt erhalten';onArchive();}
 $('#guided-mode').onclick=start;$('#archive-mode').onclick=pause;$('#journal-button').onclick=()=>showJournal();
 return {start,pause,onSquare,isActive:()=>active,refreshCapabilities(){const group=$('#connected-model');if(group)group.hidden=!isLive();}};
}
