import {newGame,moveSafely,reply} from './logic.js';
import {rules} from './content.js';
export const stages=[
 ['opening',0,'Ein Zug. Und ein Verdacht.'],['first',0,'Woran erkennst du Intelligenz?'],['investigate',0,'Was willst du wissen?'],['revised',0,'Derselbe Zug. Ein anderer Urheber.'],
 ['baronin',1,'Du führst Regie.'],['resistance',1,'Die Figur widerspricht.'],['sophie',1,'Wissen verändert die Partie.'],['carl',1,'Wer darf den nächsten Zug machen?'],['julie',1,'Diese Figur gehört sich selbst.'],['agency',1,'Hilfe oder Kontrolle?'],['book',1,'Ein Buch führt deine Hand.'],
 ['outside',2,'Von aussen: eine passende Antwort.'],['room',2,'Jetzt sitzt du im Zimmer.'],['inside',2,'Von innen: dieselbe Leistung?'],['position',2,'Wer könnte hier verstehen?'],
 ['output',3,'Eine Antwort, die du prüfen kannst.'],['audit',3,'Drei Prüfsteine.'],['network',3,'Was steckt unter diesem Zug?'],['final',3,'Was gilt jetzt als intelligent?'],['ending',3,'Das Brett deiner Urteile.']
].map(([id,era,title])=>({id,era,title}));
export const ratingStages=['first','revised','agency','outside','inside','position','audit','final'];
export const routes={
 gift:{label:'Mit Schmuck überzeugen',from:'e7',to:'d4',outcome:'Du hast Schmuck als Argument eingesetzt. Julie weist die Vorstellung zurück, man könne sie kaufen. Die Baronin zwingt sie, den Schmuck zu behalten – Zustimmung gewinnt sie dadurch nicht.',source:'III. Aufzug, 4. Auftritt'},
 debt:{label:'Wendheim unter Druck setzen',from:'d6',to:'f4',outcome:'Du hast seine Geldnot zum Druckmittel gemacht. Wendheim verweigert die geforderte Flucht. Er bleibt und nimmt eher Arrest in Kauf. Dein Zug erhöht den Druck, bestimmt aber nicht seine Entscheidung.',source:'III. Aufzug, 5 und 11. Auftritt'},
 listen:{label:'Julie nach ihrer Wahl fragen',from:'d6',to:'c4',outcome:'Deine Spielvariante eröffnet Julie das Wort. Sie bleibt bei Wendheim. Damit gibst du das ursprüngliche Ziel der Baronin auf. Im Stück fragt die Baronin hier nicht ergebnisoffen; erst Rink stimmt später Julies Wahl zu.',source:'Spielvariante; Vergleich: III, 3–4 und IV, 10'}
};
export const intelligence=['Die Leistung spricht für Intelligenz','Die Beobachtung reicht mir nicht','Ich lasse das Urteil offen'];
export const understanding=['Ja, hier wird verstanden','Nein, hier wird nur ausgeführt','Ich kann es nicht entscheiden'];
export const choiceSets={first:intelligence,revised:intelligence,agency:['Carl ermöglicht Freiheit','Carl verfügt selbst über andere','Beides bleibt miteinander verbunden'],outside:understanding,inside:understanding,position:['Die ausführende Person','Das gesamte System','Ein System in Interaktion mit der Welt'],audit:['Am Text tragfähig','Teilweise tragfähig','Am Text nicht tragfähig'],final:['Mein Kriterium bleibt bestehen','Ich verändere mein Kriterium','Ich lasse die Frage bewusst offen']};
export function freshState(){return {version:1,step:0,moves:[],records:{},inspected:[],revealed:false,route:null,routeMoved:false,message:null,informed:false,plan:null,consent:false,partnerMoved:false,bookMoves:0,ruleIndex:0,output:'',origin:'',audit:[],network:[]};}
export function canAdvance(s){const id=stages[s.step]?.id;if(ratingStages.includes(id))return !!s.records[id]?.choice&&s.records[id].reason.trim().length>=12&&(id!=='audit'||s.audit.length===3);return {opening:s.moves.length>=4,investigate:s.inspected.length>0&&s.revealed,baronin:s.routeMoved,resistance:true,sophie:!!s.message,carl:!!s.plan,julie:s.consent&&s.partnerMoved,book:s.bookMoves===2,room:s.ruleIndex===3,output:s.output.trim().length>=30&&!!s.origin,network:s.network.length===3,ending:false}[id]===true;}
export function playPosition(s){const g=newGame();for(const m of s.moves)g.move(m);return g;}
export function act(s,event){const next=structuredClone(s),id=stages[s.step].id;let notice='';
 const reject=message=>({state:s,notice:message,changed:false});
 if(event.type==='next'){if(!canAdvance(s))return reject('Führe zuerst den Zug aus oder begründe dein Urteil (mindestens 12 Zeichen).');next.step++;}
 else if(event.type==='record'){if(!ratingStages.includes(id)||!choiceSets[id].includes(event.choice)||typeof event.reason!=='string')return reject('Wähle eine Position und begründe sie.');next.records[id]={choice:event.choice,reason:event.reason.slice(0,2000)};}
 else if(id==='opening'&&event.type==='move'){if(s.moves.length>=4)return reject('Die erste Beobachtung ist abgeschlossen.');const g=playPosition(s),m=moveSafely(g,event.from,event.to);if(!m)return reject('Dieser Zug ist nicht erlaubt. Wähle eines der angezeigten Ziele.');const r=reply(g);next.moves=g.history();notice='Dein Zug: '+m.san+'. Antwort: '+(r?.san||'—')+'.';}
 else if(id==='investigate'&&event.type==='inspect'){if(!['Figur','Mechanik','Hohlraum'].includes(event.target))return reject('Unbekannter Untersuchungsort.');if(!next.inspected.includes(event.target))next.inspected.push(event.target);}
 else if(id==='investigate'&&event.type==='reveal'){if(!s.inspected.length)return reject('Untersuche zuerst einen Bereich.');next.revealed=true;}
 else if(id==='baronin'&&event.type==='route'){if(s.routeMoved||!routes[event.route])return reject('Dieser Zug steht bereits fest.');next.route=event.route;}
 else if(id==='baronin'&&event.type==='move'){const r=routes[s.route];if(!r||event.from!==r.from||event.to!==r.to)return reject('Wähle zuerst deinen Plan und führe den angegebenen Zug aus.');next.routeMoved=true;notice='Dein Zug steht. Im nächsten Bild antwortet die andere Figur.';}
 else if(id==='sophie'&&event.type==='message'){if(s.message||!['carl','julie','silence'].includes(event.to))return reject('Die Nachricht hat ihren Weg bereits genommen.');next.message=event.to;next.informed=event.to==='carl';notice={carl:'Carl kennt jetzt den Plan des Kastens.',julie:'Julie weiss Bescheid. Carl besitzt diese Information noch nicht.',silence:'Du hältst die Nachricht zurück. Carl kann den Kastenwechsel nicht planen.'}[event.to];}
 else if(id==='carl'&&event.type==='ask'){next.informed=true;notice=s.message==='julie'?'Julie zieht Carl ins Vertrauen. Jetzt kennt auch er den Plan.':'Carl fragt bei Sophie nach. Die Nachricht erreicht ihn jetzt.';}
 else if(id==='carl'&&event.type==='plan'){if(s.plan||!['box','public'].includes(event.plan))return reject('Der Plan steht bereits.');if(event.plan==='box'&&!s.informed)return reject('Carl fehlt die Information über den Kasten. Frage zuerst nach.');next.plan=event.plan;notice=event.plan==='box'?'Carl übernimmt den ersten Kasten. Der Spieler wird selbst zur vermeintlichen Maschine.':'Du wählst eine offene Konfrontation. Diese Möglichkeit ist deine Spielvariante, nicht Becks Ablauf.';}
 else if(id==='julie'&&event.type==='consent'){next.consent=true;notice='Julie entscheidet sich selbst für Wendheim. Jetzt darfst du ihn an ihre Seite stellen: F3 → D3.';}
 else if(id==='julie'&&event.type==='move'){if(!s.consent)return reject('Julie widerspricht: Über meine Verbindung entscheidet ihr nicht ohne mich. Frage sie zuerst.');if(event.from!=='f3'||event.to!=='d3')return reject('Julie bleibt auf ihrem Feld. Stelle Wendheim von F3 nach D3 an ihre Seite.');next.partnerMoved=true;notice='Wendheim steht an Julies Seite – nach ihrer eigenen Entscheidung.';}
 else if(id==='book'&&event.type==='move'){const expected=[['e2','e4'],['e7','e5']][s.bookMoves];if(!expected||event.from!==expected[0]||event.to!==expected[1])return reject('Führe genau die Vorgabe des Buchs aus.');next.bookMoves++;notice='Du hast die Vorgabe ausgeführt.';}
 else if(id==='room'&&event.type==='move'){const r=rules[s.ruleIndex];if(!r||event.from!=='a2'||event.to!==r.to)return reject('Nimm die Antwortfigur auf A2 und setze sie auf das in der Regel genannte Feld.');next.ruleIndex++;notice='Die Zuordnung stimmt. Über Verständnis ist damit noch nichts entschieden.';}
 else if(id==='output'&&event.type==='output'){if(typeof event.text!=='string'||!['Extern eingefügte Modellantwort (Herkunft selbst angegeben)','Live-Modellantwort','Redaktioneller Textvergleich – keine KI-Inferenz'].includes(event.origin))return reject('Eine Antwort mit Herkunft wird benötigt.');next.output=event.text.slice(0,6000);next.origin=event.origin;}
 else if((id==='audit'||id==='network')&&event.type==='check'){const choices=id==='audit'?['Sprache','Beleg','Schlussfolgerung']:['Daten','Training','Inferenz'];if(!choices.includes(event.target))return reject('Unbekannter Prüfstein.');if(!next[id].includes(event.target))next[id].push(event.target);}
 else return reject('Dieser Zug gehört nicht zur aktuellen Szene.');
 return {state:next,notice,changed:true};
}
export function restoreState(raw){try{if(!raw||raw.length>60000)return null;const s=JSON.parse(raw),base=freshState();if(s.version!==1||!Number.isInteger(s.step)||s.step<0||s.step>=stages.length)return null;
 for(const key of ['moves','inspected','audit','network'])if(!Array.isArray(s[key])||s[key].some(x=>typeof x!=='string')||s[key].length>10)return null;
 for(const key of ['revealed','routeMoved','informed','consent','partnerMoved'])if(typeof s[key]!=='boolean')return null;
 for(const [key,max] of [['bookMoves',2],['ruleIndex',3]])if(!Number.isInteger(s[key])||s[key]<0||s[key]>max)return null;
 if(s.route!==null&&!routes[s.route]||s.message!==null&&!['carl','julie','silence'].includes(s.message)||s.plan!==null&&!['box','public'].includes(s.plan))return null;
 if(typeof s.output!=='string'||s.output.length>6000||typeof s.origin!=='string'||!s.records||typeof s.records!=='object'||Array.isArray(s.records))return null;
 for(const [id,r]of Object.entries(s.records))if(!choiceSets[id]?.includes(r?.choice)||typeof r.reason!=='string'||r.reason.length>2000)return null;
 playPosition(s);for(const k of Object.keys(base))base[k]=s[k];return base;
 }catch{return null;}}
export function journalText(s){const lines=['DIE SCHACHMASCHINE — Mein Brett der Urteile','Kein Punktestand. Beobachtungen, Entscheidungen und Gründe.',''];for(const stage of stages){const r=s.records[stage.id];if(r)lines.push(stage.title,r.choice,r.reason,'');}lines.push('Untersucht: '+s.inspected.join(' → '),'Plan der Baronin: '+(routes[s.route]?.label||'noch offen'),'Sophies Nachricht: '+({carl:'an Carl',julie:'an Julie',silence:'zurückgehalten'}[s.message]||'noch offen'),'Carls Plan: '+({box:'Kastenwechsel',public:'offene Konfrontation (Spielvariante)'}[s.plan]||'noch offen'),'Julies Entscheidung erfragt: '+(s.consent?'ja':'noch nicht'),'','Untersuchte Antwort — '+(s.origin||'noch keine'),s.output,'','Textbezug: Heinrich Beck, Die Schachmaschine, III. Aufzug, 4. Auftritt. Arbeitsgrundlage: geliefertes Transkript, kein Faksimileabgleich.');return lines.join('\n');}
