import {stages} from './journey-state.js';
const API=import.meta.env.VITE_MULTIPLAYER_API||'https://die-schachmaschine-multiplayer.patrick-fischer.workers.dev';
const KEY='schachmaschine-room-v1';
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
export function createMultiplayer(journey){
 let session=null,snapshot=null,busy=false,timer=null,connected=false;
 const panel=el('section');panel.className='multiplayer-panel';panel.hidden=true;document.querySelector('.mode-bar').after(panel);
 const launch=el('button','Multiplayer · 2–5');launch.id='multiplayer-mode';document.querySelector('.mode-buttons').append(launch);
 const dialog=el('dialog');dialog.id='multiplayer-lobby';document.body.append(dialog);
 const message=el('p');message.setAttribute('role','status');
 const controls=el('div');panel.append(controls,message);
 const button=(parent,label,fn)=>{const b=el('button',label);b.type='button';b.onclick=fn;parent.append(b);return b;};
 const say=text=>message.textContent=text;
 function save(){try{if(session)sessionStorage.setItem(KEY,JSON.stringify(session));else sessionStorage.removeItem(KEY);}catch{say('Sitzungsspeicher nicht verfügbar. Halte diesen Tab geöffnet.');}}
 async function request(path,body,token=session?.token){const response=await fetch(API+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Verbindung fehlgeschlagen.');return data;}
 function apply(data){if(snapshot&&data.revision<snapshot.revision)return;const rosterChanged=JSON.stringify(snapshot?.members)!==JSON.stringify(data.members);const changed=!snapshot||snapshot.revision!==data.revision;snapshot=data;connected=true;panel.hidden=false;if(changed||rosterChanged)draw();if(data.started&&(changed||!journey.isMultiplayer()))journey.receiveRoom(data,send);}
 async function poll(){clearTimeout(timer);if(!session||busy)return schedule();try{apply(await request('/rooms/'+session.code+'/state'));say('Verbunden · Spielstand synchronisiert');}catch(e){connected=false;draw();say(e.message+' Deine Eingaben bleiben erhalten.');}schedule();}
 function schedule(){clearTimeout(timer);if(session)timer=setTimeout(poll,2000);}
 async function send(event){if(!session||busy)return false;busy=true;draw();try{const data=await request('/rooms/'+session.code+'/action',{...event,step:snapshot.state.step,revision:snapshot.revision});if(data.closed){leave();return true;}apply(data);say('Gemeinsamer Spielstand gespeichert.');return true;}catch(e){say(e.message);return false;}finally{busy=false;draw();schedule();}}
 function leave(){clearTimeout(timer);session=null;snapshot=null;connected=false;save();lock();panel.hidden=true;journey.leaveRoom();const url=new URL(location.href);url.searchParams.delete('room');history.replaceState(null,'',url);}
 function invite(){const url=new URL(location.href);url.search='';url.searchParams.set('room',session.code);return url.href;}
 function lock(){document.querySelector('main').inert=!!session&&(!snapshot?.started||busy||!connected);document.querySelector('footer').inert=!!session;for(const id of ['guided-mode','archive-mode'])document.getElementById(id).disabled=!!session;}
 function draw(){lock();controls.replaceChildren();if(!snapshot){if(session)button(controls,'Gespeicherten Raumzugang vergessen',leave);return;}const title=el('h2','Raum '+session.code);controls.append(title);const stage=stages[snapshot.state.step];const actor=snapshot.members.find(m=>m.id===snapshot.actor);controls.append(el('p',snapshot.started?stage.title+' · Am Zug: '+actor?.name:'Warteraum · '+snapshot.members.length+' / 5 Personen'));
 const roster=el('ul');roster.className='room-roster';for(const m of snapshot.members){const li=el('li',m.name+(m.id===snapshot.me?' (du)':'')+(m.id===snapshot.host?' · Raumleitung':'')+' · '+(!m.online?'getrennt':m.ready?'bereit':m.submitted?'Urteil abgegeben':'verbunden'));roster.append(li);if(snapshot.me===snapshot.host&&!m.online&&m.id!==snapshot.me)button(li,'Entfernen',()=>send({type:'remove',target:m.id}));}controls.append(roster);
 if(!snapshot.started){const input=el('input');input.readOnly=true;input.value=invite();input.setAttribute('aria-label','Einladungslink');controls.append(input);button(controls,'Einladungslink kopieren',async()=>{try{await navigator.clipboard.writeText(invite());say('Link kopiert.');}catch{input.select();say('Markierten Link kopieren.');}});if(snapshot.me===snapshot.host){const b=button(controls,'Partie mit allen starten',()=>send({type:'start'}));b.disabled=busy||snapshot.members.length<2;}controls.append(el('p','2–5 Personen, je ein Gerät oder Browser-Tab. Erst starten, wenn alle da sind. Die Rollen wechseln; jede Person urteilt selbst.'));}
 else {const me=snapshot.members.find(m=>m.id===snapshot.me);if(stage.id!=='ending'){const ready=button(controls,me.ready?'Bereit ✓ · zurücknehmen':'Ich bin bereit',()=>send({type:'ready',ready:!me.ready}));ready.disabled=busy||!connected||!snapshot.complete;}const revealed=snapshot.comparisons[stage.id];if(revealed){const group=el('details');group.open=true;group.append(el('summary','Unsere Urteile · Unterschiede besprechen'));for(const r of revealed){const card=el('article');card.append(el('strong',r.name),el('p',r.choice),el('p',r.reason));group.append(card);}controls.append(group);}else if(snapshot.submitted)controls.append(el('p','Dein Urteil ist abgegeben. Die anderen Urteile erscheinen, sobald alle abgegeben haben.'));
 if(stage.id==='ending')button(controls,'Gemeinsame Zugspur sichern',()=>{const lines=['DIE SCHACHMASCHINE — Gemeinsame Zugspur'];for(const s of stages){const entries=snapshot.comparisons[s.id];if(entries){lines.push('',s.title);for(const r of entries)lines.push(r.name+': '+r.choice,r.reason);}}const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=el('a');a.href=url;a.download='schachmaschine-gruppenspur.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
 if(!snapshot.members.find(m=>m.id===snapshot.host)?.online)button(controls,'Raumleitung übernehmen',()=>send({type:'claim'}));
 button(controls,'Raum verlassen',()=>{if(confirm('Diesen Raum verlassen? Ohne diesen Tab-Zugang kannst du einer laufenden Partie nicht erneut beitreten.'))leave();});if(snapshot.me===snapshot.host)button(controls,'Raum für alle schliessen',()=>{if(confirm('Raum für alle schliessen und gespeicherte Urteile löschen? Sichere vorher die Zugspuren.'))send({type:'close'});});
 controls.append(el('p','Pseudonyme und Urteile werden im Raumserver bis zu 24 Stunden gespeichert, danach gelöscht. Nur Personen mit Raumzugang sehen die freigegebenen Urteile. Keine Übertragung an ein Sprachmodell.'));
 }
 function lobby(){if(session){panel.hidden=false;poll();return;}dialog.replaceChildren();dialog.append(el('h2','Gemeinsam am Brett'),el('p','Ein Raum, 2–5 Perspektiven. Spielt auf getrennten Geräten und besprecht eure Beobachtungen.'));
 const nameLabel=el('label','Dein Pseudonym');const name=el('input');name.maxLength=24;name.autocomplete='off';nameLabel.append(name);dialog.append(nameLabel);
 const codeLabel=el('label','Raumcode');const code=el('input');code.maxLength=12;code.value=new URL(location.href).searchParams.get('room')||'';code.autocomplete='off';codeLabel.append(code);dialog.append(codeLabel);const error=el('p');error.setAttribute('role','status');dialog.append(error);
 async function enter(join){if(!name.value.trim()){error.textContent='Gib ein Pseudonym ein.';return;}const value=code.value.trim().toUpperCase();if(join&&!/^[A-F0-9]{12}$/.test(value)){error.textContent='Der Raumcode besteht aus 12 Zeichen.';return;}for(const b of dialog.querySelectorAll('button'))b.disabled=true;try{const data=await request(join?'/rooms/'+value+'/join':'/rooms',{name:name.value.trim()},null);session={code:data.code,token:data.token};save();apply(data);dialog.close();schedule();}catch(e){error.textContent=e.message;}finally{for(const b of dialog.querySelectorAll('button'))b.disabled=false;}}
 button(dialog,'Neuen Raum erstellen',()=>enter(false));button(dialog,'Raum beitreten',()=>enter(true));button(dialog,'Schliessen',()=>dialog.close());dialog.showModal();name.focus();}
 launch.onclick=lobby;
 try{const saved=JSON.parse(sessionStorage.getItem(KEY));if(saved&&/^[A-F0-9]{12}$/.test(saved.code)&&/^[a-f0-9]{48}$/.test(saved.token))session=saved;}catch{}
 if(session){lock();panel.hidden=false;button(controls,'Gespeicherten Raumzugang vergessen',leave);poll();}else if(new URL(location.href).searchParams.has('room'))lobby();
 return {lobby};
}
