import {createPerspectiveUI} from './perspective-ui.js';
import {stages,roles,pages,freshState,act,canAdvance,restore,journalText} from './play-state.js';
const KEY='schachmaschine-whole-play-v1';
const $=s=>document.querySelector(s);
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function button(p,text,fn,cls=''){const b=n('button',text,cls);b.type='button';b.onclick=fn;p.append(b);return b;}
export function createPlay({scene,drawBoard,onStart}){
 let state=freshState(),history=[],active=false,room=null,send=null,solo=null,storage=true,selectedRole=null;const drafts={};const perspectives=createPerspectiveUI({scene,drawBoard,onSquare,dispatch});
 try{state=restore(localStorage.getItem(KEY))||state;history=(JSON.parse(localStorage.getItem(KEY+'-undo'))||[]).slice(-80).map(s=>restore(JSON.stringify(s))).filter(Boolean);}catch{storage=false;}
 const mode=button($('.mode-buttons'),'Das ganze Stück',start);mode.id='play-mode';$('.mode-buttons').prepend(mode);
 const notebook=n('dialog',undefined,'reading-dialog');notebook.setAttribute('aria-label','Leseprotokoll');document.body.append(notebook);
 function save(){if(room)return;try{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(KEY+'-undo',JSON.stringify(history));}catch{storage=false;}}
 function dispatch(event,render=true){if(room){send(event);return;}const r=act(state,event);if(!r.changed){$('#status').textContent=r.notice;return;}if(event.type!=='record'){history.push(structuredClone(state));history=history.slice(-80);while(new TextEncoder().encode(JSON.stringify(history)).length>524288)history.shift();}state=r.state;save();if(render)show();}
 function download(text,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=n('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function journal(){notebook.replaceChildren();button(notebook,'× Schliessen',()=>notebook.close());notebook.append(n('h2','Mein Leseprotokoll'),n('pre',journalText(state),'play-journal'));button(notebook,'Protokoll als Text sichern',()=>download(journalText(state),'schachmaschine-lektüre.txt'));if(!room){button(notebook,'Lesestand als Datei sichern',()=>download(JSON.stringify(state),'schachmaschine-lesestand.json','application/json'));const label=n('label','Gesicherten Lesestand laden');const file=n('input');file.type='file';file.accept='.json,application/json';const status=n('p');file.onchange=async()=>{const f=file.files[0];if(!f)return;if(f.size>6000000){status.textContent='Diese Datei ist zu gross.';return;}const restored=restore(await f.text());if(!restored){status.textContent='Das ist kein gültiger Lesestand.';return;}if(!confirm('Aktuellen Lesestand durch diese Sicherung ersetzen?'))return;state=restored;history=[];save();notebook.close();show();};label.append(file);notebook.append(label,status);}notebook.append(n('p',room?'Der gemeinsame Lektüreraum bleibt sieben Tage bestehen. Über Multiplayer kannst du den auf diesem Gerät gesicherten Zugang wieder öffnen. Sichere vor Ablauf dein Leseprotokoll.':storage?'Lesestand und Beobachtungen bleiben auf diesem Gerät gespeichert. Für einen Gerätewechsel sichere die Lesestand-Datei.':'Der Gerätespeicher ist nicht verfügbar. Sichere vor dem Schliessen die Lesestand-Datei.','source-note'));notebook.showModal();}
 function onSquare(square){if(active)perspectives.selectSquare(square);}
 function renderText(parent,text){const article=n('article',undefined,'staged-transcript');article.id='staged-transcript';article.setAttribute('aria-label','Originaltext dieser Textstrecke');const re=/(?:^|(?<=[.!?\n)]))[ \t]*(?:Baroninn?|Baron|Julie|Sophie|Carl|Wendheim|Graf|Ruf|Frey|Flucht|Marie|Salden|Bedienter|Erster Träger|Zweyter Träger)[.:](?=\s|$)|\([^)]*\)/g;let at=0;for(const match of text.matchAll(re)){article.append(document.createTextNode(text.slice(at,match.index)));article.append(n(match[0].startsWith('(')?'em':'strong',match[0],match[0].startsWith('(')?'stage-direction':'stage-speaker'));at=match.index+match[0].length;}article.append(document.createTextNode(text.slice(at)));parent.append(article);}
 function navigation(c){const nav=n('div',undefined,'journey-navigation');const back=button(nav,'↶ Zug zurück',()=>{if(room){if(confirm('Letzten gemeinsamen Leseschritt für alle zurücknehmen?'))send({type:'undo'});}else{state=history.pop();save();show();}});back.disabled=room?room.me!==room.host||!room.canUndo:!history.length;back.id='play-undo';const reset=button(nav,'Reset · Neu beginnen',()=>{if(!confirm('Diese vollständige Lektüre neu beginnen? Das Leseprotokoll wird gelöscht.'))return;if(room)send({type:'reset'});else{state=freshState();history=[];perspectives.resetDrafts();save();show();}});reset.disabled=!!room&&room.me!==room.host;const stage=stages[state.step];if(stage.kind!=='ending'){const next=button(nav,room?'Gemeinsam weiterlesen':stage.kind==='reflection'?'Nächsten Aufzug öffnen':'Textstrecke gelesen · Weiter',()=>dispatch({type:'next'}),'primary');next.id='play-next';next.disabled=room?room.me!==room.host||!room.complete||!room.members.every(m=>m.ready):!canAdvance(state);}button(nav,'Leseprotokoll / Speichern',journal);c.append(nav);}
 function show(){if(!active)return;const stage=stages[state.step],c=$('#scene-controls');document.body.classList.add('guided','whole-play');for(const [id,on]of [['play-mode',true],['guided-mode',false],['archive-mode',false]])$('#'+id).setAttribute('aria-pressed',String(on));$('#journal-button').textContent='Mein Leseprotokoll ↗';$('#journal-button').onclick=journal;
 $('#title').textContent=stage.title;$('#intro').textContent='';$('#eyebrow').textContent='BECK · DER VOLLSTÄNDIGE TEXT ALS BÜHNENPARTIE';const read=stages.slice(0,state.step).filter(s=>s.kind==='text').length;$('#journey-progress').textContent=read+' / '+pages.length+' Textstrecken durchlaufen';$('#chapter-count').textContent=stage.kind==='text'?'Textstrecke '+stage.part+' / '+stage.parts:stage.kind==='reflection'?'AUFZUGSPAUSE':'SCHLUSS';$('#material').textContent='FIGUREN / BEZIEHUNGEN';$('#board-caption').textContent='PERSPEKTIVEN · TEXTBELEGE · REVISIONEN';$('#status').textContent='';for(const id of ['question','reveal'])$('#'+id).replaceChildren();for(const id of ['open','layers','compare','reset','archive-undo'])$('#'+id).hidden=true;c.replaceChildren();
 scene.setTheme(1);scene.showLayers([]);scene.open(false,1);
 if(state.step===0)c.append(n('p','Lies und inszeniere das vollständige Lustspiel von Heinrich Beck (1798): vier Aufzüge, 44 Auftritte, rund 20.400 Wörter. Plane mehrere Sitzungen ein. Das Original bleibt ungekürzt; wir teilen es nur in lesbare Strecken.','journey-intro'),n('p','Lies allein oder mit verteilten Stimmen. An 14 Schlüsselstellen gestaltet ihr Beziehungen mit markierten Textbelegen und vergleicht Figurenperspektiven. Frühere Lesarten können mit späteren Belegen revidiert werden. Die Kameraperspektive und die Deutungsperspektive sind unabhängig wählbar.'),n('p','Die Sprechrollen werden im Multiplayer auf die Teilnehmenden verteilt. Alle sehen denselben Text und bestätigen ihr Weiterlesen selbst. Der Fortschritt dokumentiert bestätigte Textstrecken, nicht überprüftes Verständnis.','source-note'));
 if(room){const cast=n('details',undefined,'role-cast');cast.append(n('summary','Eure Rollenbesetzung'));for(let i=0;i<roles.length;i++)cast.append(n('p',roles[i].name+' → '+room.members[i%room.members.length].name));c.append(cast);}
 if(stage.kind==='text'){const r=roles[stage.roleIndex];const call=n('div',undefined,'move-instruction');call.append(n('p','Lesemoderation: '+r.name+(room?' · '+room.members.find(m=>m.id===room.actor)?.name:'')));if(!state.opened){const open=button(call,'Textstrecke öffnen',()=>dispatch({type:'open',role:stage.roleIndex}),'primary');open.id='play-open';open.disabled=!!room&&room.actor!==room.me;call.append(n('p','Öffne den Originaltext. Das Brett zeigt eure belegten Beziehungen und unterscheidet die Sichtweisen der Figuren.'));}c.append(call);if(state.opened){c.append(n('p','ORIGINALTEXT · '+(stage.act?stage.title:'Titel und Personenverzeichnis'),'eyebrow'));renderText(c,stage.text);c.append(n('p','Lest die Sprecherwechsel mit verteilten Stimmen. Bei einem längeren Wortbeitrag könnt ihr die Lesestimme weitergeben. Regieanweisungen können gesprochen oder auf dem Brett vorgestellt werden.','source-note'));}c.append(n('p','Textgrundlage: bereitgestelltes Transkript. Historische Schreibweisen und Übertragungsfehler sind unverändert; bei unklaren Stellen gemeinsam innehalten.','source-note'));}
 else if(stage.kind==='reflection'){c.append(n('p','Aufzugspause: Vergleiche eure belegten Beziehungen. Welche frühere Lesart trägt noch, welche hat sich verändert? Gestalte mindestens eine Beziehung aus diesem Aufzug und fasse deine Beobachtung zusammen.','journey-intro'));c.append(n('p',stage.prompt));const r=state.records[stage.id]||drafts[stage.id]||{reason:''};const label=n('label','Deine Beobachtung mit Textbeleg');label.htmlFor='play-reason';const area=n('textarea');area.id='play-reason';area.rows=6;area.maxLength=2000;area.value=r.reason;area.placeholder='Die Stelle … zeigt für mich … Offen bleibt …';area.disabled=!!room?.submitted;area.oninput=()=>{if(room)drafts[stage.id]={reason:area.value};else dispatch({type:'record',reason:area.value},false);const next=$('#play-next');if(next&&!room)next.disabled=!canAdvance(state);};c.append(label,area,n('p','Freie Antwort, mindestens 12 Zeichen. Keine Musterlösung und keine MC-Frage.','source-note'));if(room){const submit=button(c,room.submitted?'Beobachtung abgegeben':'Beobachtung abgeben',()=>send({type:'record',reason:area.value}),'primary');submit.disabled=room.submitted;}else c.append(n('p','Dein Entwurf wird auf diesem Gerät gespeichert.'));}
 else{c.append(n('p','Alle 44 Auftritte und alle '+pages.length+' Textstrecken sind durchlaufen – einschliesslich Titel, Personen und Schluss. Vergleicht jetzt eure vier Beobachtungen: Wie werden im Stück Menschen zu Spielern, Figuren oder Maschinen?','journey-intro'));for(const [id,r]of Object.entries(state.records))c.append(n('h3',stages.find(s=>s.id===id).title),n('p',r.reason));c.append(n('p','Die zusätzliche Themenpartie verbindet diese Lektüre mit Kempelen, Searle und heutigen KI-Antworten. Sie bleibt über „Themenpartie“ zugänglich.'));}
 perspectives.render(c,state,stage,room);navigation(c);const timeline=$('#timeline');timeline.replaceChildren();for(let a=1;a<=4;a++){const x=n('div',undefined,'guided-era');x.setAttribute('aria-current',stage.act===a?'step':'false');x.append(n('span',['I','II','III','IV'][a-1],'year'),n('span','Aufzug'));timeline.append(x);}}
 function start(){onStart();selectedRole=null;active=true;scene.view('default');show();}
 function pause(){active=false;perspectives.hide();$('#play-mode').setAttribute('aria-pressed','false');document.body.classList.remove('whole-play');$('#reset').hidden=false;$('#archive-undo').hidden=false;}
 return {start,pause,onSquare,isActive:()=>active,isMultiplayer:()=>!!room,receiveRoom(s,fn){if(!room)solo=structuredClone(state);if(room?.epoch!==s.epoch)for(const k of Object.keys(drafts))delete drafts[k];room=s;send=fn;state=structuredClone(s.state);onStart();active=true;show();},leaveRoom(){if(!room)return;room=null;send=null;state=solo||freshState();solo=null;start();}};
}
