import {checkpoint} from './dramaturgy.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(parent,text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;parent.append(b);return b;};
// Preserve source text and offsets: wrapping a turn never rewrites a character.
export function speechTurns(text,initialSpeaker=null){const names='Baroninn?|Baron|Julie|Sophie|Carl|Wendheim|Graf|Ruf|Frey|Flucht|Marie|Salden|Bedienter|Erster Träger|Zweyter Träger';const re=new RegExp('(?:^|(?<=[.!?\\n)]))[ \\t]*('+names+')[.:](?=\\s|$)','g');const matches=[...text.matchAll(re)];const turns=[];let start=0,speaker=initialSpeaker;for(const m of matches){if(m.index>start)turns.push({start,end:m.index,speaker});start=m.index;speaker=m[1];}if(start<text.length)turns.push({start,end:text.length,speaker});return turns;}
export function createReadingStage({scene,roles,pages,onEvidence}){
 const main=document.querySelector('main'),reader=main.querySelector('aside'),accessible=main.querySelector('.accessible');
 let active=false,key='',scroll=0,drawerScroll=0,anchor=null,observer=null,currentStage=null,split=60,layout='stack',drawerOpen=false;
 try{const pref=JSON.parse(localStorage.getItem('schachmaschine-layout')||'{}');if(['stack','side'].includes(pref.layout))layout=pref.layout;if(Number.isFinite(pref.split))split=Math.max(35,Math.min(70,pref.split));}catch{}
 window.addEventListener('resize',()=>{if(active)apply();});
 const save=()=>{try{localStorage.setItem('schachmaschine-layout',JSON.stringify({layout,split}));}catch{}};
 const tools=el('div',null,'reading-tools');document.querySelector('.world-top').after(tools);
 const view=el('select');view.id='reading-layout';view.setAttribute('aria-label','Anordnung von Brett und Text');for(const [v,t]of [['stack','Bühne oben · Text unten'],['side','Brett links · Text rechts']]){const o=el('option',t);o.value=v;view.append(o);}view.value=layout;view.onchange=()=>{layout=view.value;apply();save();};view.title='Die Trennlinie lässt sich ziehen oder mit den Pfeiltasten bewegen.';tools.append(view);
 const toggle=button(tools,'Werkstatt öffnen',()=>setDrawer(!drawerOpen));toggle.id='workshop-toggle';toggle.setAttribute('aria-controls','interpretation-drawer');
 const look=el('div',null,'board-perspectives');tools.append(look);new ResizeObserver(()=>{const world=document.querySelector('.world');world.style.setProperty('--reading-toolbar-height',(tools.offsetTop+tools.offsetHeight+4)+'px');}).observe(tools);
 const caption=el('p','', 'stage-relation-summary');caption.id='stage-relation-summary';caption.setAttribute('aria-live','polite');document.querySelector('.world').append(caption);
 const splitter=el('div',null,'reading-splitter');splitter.tabIndex=0;splitter.setAttribute('role','separator');splitter.setAttribute('aria-label','Platz für Bühne und Text verändern');splitter.setAttribute('aria-valuemin','35');splitter.setAttribute('aria-valuemax','70');main.append(splitter);
 const drawer=el('section',null,'interpretation-drawer');drawer.id='interpretation-drawer';drawer.setAttribute('aria-label','Interpretationswerkstatt');const head=el('div',null,'drawer-heading');head.append(el('strong','Interpretationswerkstatt'));button(head,'Werkstatt schliessen',()=>{setDrawer(false);toggle.focus();});const body=el('div',null,'drawer-content');drawer.append(head,body);main.append(drawer);
 const pin=el('section',null,'text-anchor');pin.id='text-anchor';pin.setAttribute('aria-label','Festgehaltene Textstelle');reader.querySelector('#scene-controls').before(pin);
 function apply(){main.dataset.readingLayout=layout;main.style.setProperty('--board-share',split+'%');splitter.setAttribute('aria-valuenow',String(Math.round(split)));splitter.setAttribute('aria-orientation',layout==='side'&&innerWidth>850?'vertical':'horizontal');}
 function setDrawer(open){drawerOpen=open;drawer.hidden=!open;toggle.textContent=open?'Werkstatt schliessen':checkpoint(currentStage||{})?'Werkstatt · Perspektivvergleich':'Werkstatt öffnen';toggle.setAttribute('aria-expanded',String(open));main.classList.toggle('workshop-open',open);}
 function setSplit(value){split=Math.max(35,Math.min(70,value));apply();save();}
 splitter.onkeydown=e=>{if(['ArrowUp','ArrowLeft','ArrowDown','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();setSplit(e.key==='Home'?35:e.key==='End'?70:split+(['ArrowUp','ArrowLeft'].includes(e.key)?-3:3));}};
 splitter.onpointerdown=e=>{splitter.setPointerCapture(e.pointerId);e.preventDefault();};splitter.onpointermove=e=>{if(!splitter.hasPointerCapture(e.pointerId))return;const r=main.getBoundingClientRect();setSplit(layout==='side'&&innerWidth>850?(e.clientX-r.left)/r.width*100:(e.clientY-r.top)/r.height*100);};splitter.onpointerup=e=>{if(splitter.hasPointerCapture(e.pointerId))splitter.releasePointerCapture(e.pointerId);};
 document.addEventListener('keydown',e=>{if(active&&e.key==='Escape'&&!document.querySelector('dialog[open]'))setDrawer(false);});
 const names={'Baroninn':1,'Baronin':1,'Baron':2,'Julie':3,'Sophie':4,'Carl':5,'Wendheim':6,'Graf':7,'Ruf':8,'Frey':9,'Flucht':10,'Marie':11,'Salden':12,'Bedienter':13,'Erster Träger':13,'Zweyter Träger':13};
 function speaker(name){scene.speaker?.(name?roles[names[name]]?.name:null);document.querySelectorAll('.speech-turn').forEach(t=>t.classList.toggle('current-speaker',t.dataset.speaker===name));}
 function pinText(start,end,speakerName){const page=pages.findIndex(p=>p.id===currentStage.id);if(page<0)return;anchor={page,start,end,speaker:speakerName};paintAnchor();speaker(speakerName);}
 function paintAnchor(){pin.replaceChildren();pin.hidden=!anchor;if(!anchor)return;pin.append(el('strong',(anchor.speaker||'Textstelle')+' · festgehalten'),el('blockquote',pages[anchor.page].text.slice(anchor.start,anchor.end)));button(pin,'Als Beleg bearbeiten',()=>{setDrawer(true);onEvidence(anchor);});button(pin,'Textanker lösen',()=>{anchor=null;paintAnchor();});}
 function annotate(article){observer?.disconnect();if(!article||currentStage.kind!=='text')return;const text=currentStage.text;let inherited=null;if(currentStage.part>1){for(const p of pages.filter(p=>p.act===currentStage.act&&p.scene===currentStage.scene&&p.part<currentStage.part))inherited=speechTurns(p.text,inherited).at(-1)?.speaker||inherited;}article.title='Äusserung anklicken oder Text markieren: als Textanker festhalten. Blau markiert die Lesestimme, Gold die gewählte Perspektive.';article.replaceChildren();for(const turn of speechTurns(text,inherited)){const span=el('span',null,'speech-turn');const content=text.slice(turn.start,turn.end);if(turn.speaker&&content.trimStart().startsWith(turn.speaker)){const offset=content.indexOf(turn.speaker)+turn.speaker.length+1;span.append(el('strong',content.slice(0,offset),'speech-name'),document.createTextNode(content.slice(offset)));}else span.textContent=content;span.dataset.speaker=turn.speaker||'';span.dataset.start=turn.start;span.dataset.end=turn.end;span.tabIndex=0;span.setAttribute('role','button');span.setAttribute('aria-label',(turn.speaker||'Textstelle')+' als Textanker festhalten');span.onclick=()=>{if(!window.getSelection()?.isCollapsed)return;pinText(turn.start,turn.end,turn.speaker);};span.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();pinText(turn.start,turn.end,turn.speaker);}};article.append(span);}
 article.addEventListener('mouseup',()=>{const selection=window.getSelection();if(!selection?.rangeCount||selection.isCollapsed)return;const r=selection.getRangeAt(0);if(!article.contains(r.startContainer)||!article.contains(r.endContainer))return;const before=r.cloneRange();before.selectNodeContents(article);before.setEnd(r.startContainer,r.startOffset);const start=before.toString().length;const turn=[...article.children].find(t=>Number(t.dataset.start)<=start&&Number(t.dataset.end)>start);pinText(start,start+r.toString().length,turn?.dataset.speaker);});
 observer=new IntersectionObserver(entries=>{if(anchor)return;const turns=[...article.children].filter(t=>{const r=t.getBoundingClientRect(),root=document.querySelector('#scene-controls').getBoundingClientRect();return r.bottom>root.top+15&&r.top<root.bottom;});if(turns[0])speaker(turns[0].dataset.speaker);},{root:document.querySelector('#scene-controls'),threshold:[0,.1,.5,1]});article.querySelectorAll('.speech-turn').forEach(t=>observer.observe(t));}
 function prepare(){drawerScroll=body.scrollTop;scroll=document.querySelector('#scene-controls')?.scrollTop||0;observer?.disconnect();if(accessible)reader.append(accessible);body.replaceChildren();look.replaceChildren();reader.querySelector('.journey-navigation')?.remove();}
 function mount(stage,state){active=true;currentStage=stage;document.body.classList.add('reading-stage');tools.hidden=false;splitter.hidden=false;caption.hidden=false;if(key!==stage.id){key=stage.id;scroll=0;drawerScroll=0;anchor=null;scene.speaker?.(null);}if(stage.kind==='text'&&!state.opened)anchor=null;apply();const workshop=document.querySelector('#perspective-workshop');if(workshop)body.append(workshop);if(accessible)body.append(accessible);for(const id of ['perspective-select','perspective-author','perspective-layer']){const select=document.getElementById(id);if(select)look.append(select.parentElement);}const nav=document.querySelector('.journey-navigation');if(nav)reader.append(nav);reader.setAttribute('aria-label','Originaltext und Lektürefortschritt');const controls=document.querySelector('#scene-controls');controls.setAttribute('tabindex','0');controls.setAttribute('aria-label','Scrollbarer Lesebereich');annotate(document.querySelector('#staged-transcript'));paintAnchor();controls.scrollTop=scroll;body.scrollTop=drawerScroll;setDrawer(drawerOpen);}
 function hide(){active=false;observer?.disconnect();scene.speaker?.(null);document.body.classList.remove('reading-stage');main.classList.remove('workshop-open');tools.hidden=true;splitter.hidden=true;drawer.hidden=true;pin.hidden=true;caption.hidden=true;if(accessible)reader.append(accessible);body.replaceChildren();look.replaceChildren();reader.querySelector('.journey-navigation')?.remove();}
 hide();return {prepare,mount,hide,openWorkshop:()=>setDrawer(true)};
}
