import {correctPassage,passagePages} from './text-edition.js';
import {editionGuide} from './edition-ui.js';
import scenes from './reading-scenes.json' with {type:'json'};
import {characters} from './content.js';
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
export const contexts={
 opening:{title:'Worum es in dieser Partie geht',text:'Heinrich Becks «Die Schachmaschine» ist ein Lustspiel in vier Aufzügen von 1798. Julie liebt Wendheim. Ihre Tante, die Baronin, möchte sie jedoch mit dem reichen Grafen Balken verheiraten; ihr Onkel Rink hat Carl Ruf vorgesehen. Die Frage ist: Können Menschen wie Schachfiguren nach dem Plan anderer bewegt werden?',bridge:'Wir beginnen beim Automaten, auf den die Baronin im Stück ausdrücklich verweist. Beobachte zuerst zwei Züge. Danach führt dich die Partie zu Becks Intrige, zum Befolgen von Regeln und zu heutigen KI-Antworten. Diese vier Stationen sind unser heutiger Vergleich; Beck schreibt kein Stück über moderne KI.',scene:'III-1',quoteKey:'kempelen'},
 first:{title:'Eine Leistung beobachten – einen Urheber vermuten',text:'Der Auftakt greift die Faszination am scheinbar selbständig spielenden Automaten auf. Du hast seine Antworten gesehen, aber damit noch nicht erklärt, wie sie zustande kommen.',bridge:'Beschreibe, was du wirklich beobachtet hast, und trenne es von deiner Vermutung. Das wird später auch bei den handelnden Personen und bei einer Modellantwort wichtig.'},
 investigate:{title:'Was die sichtbare Bühne verbirgt',text:'Im Stück wird eine angebliche Schachmaschine zum Mittel einer Intrige. Bevor du diesen Plan kennenlernst, untersuchst du hier das Verhältnis zwischen sichtbarer Bewegung und verborgenem Handelnden.',bridge:'Figur, Mechanik und Hohlraum sind Untersuchungsorte. Öffne anschliessend das System und vergleiche deine Erklärung mit deinem ersten Urteil.'},
 revised:{title:'Vom Automaten zum Menschen als Maschine',text:'Die Enthüllung verändert deine Kenntnis des Urhebers, obwohl die Züge gleich bleiben. Beck verschiebt die Frage: Ein Mensch soll selbst als «Maschine» auftreten und sich in einen fremden Plan einfügen.',bridge:'Formuliere dein neues Urteil. Danach übernimmst du eine Rolle in der Heiratsintrige.'},
 baronin:{title:'Die Ausgangslage im Haus Rink',text:'Julie ist Rinks Nichte; die Baronin ist seine Frau. Julie liebt den mittellosen Wendheim. Graf Balken, Wendheims Stiefbruder, besitzt Rang und Geld und wird von der Baronin als Bräutigam unterstützt. Rink lehnt Balken ab, will aber zunächst selbst über Julies Ehe bestimmen: Er hat Carl Ruf vorgesehen.',bridge:'Du spielst nun die Baronin. Die Brettzüge übersetzen unterschiedliche Mittel ihrer Einflussnahme. Schmuck und Druck haben Textbezüge; ergebnisoffenes Zuhören ist eine ausdrücklich erfundene Alternative. Die Felder sind eine Inszenierung und stehen nicht im Drama.',scene:'III-4',quoteKey:'refusal'},
 resistance:{title:'Eine Handlung ist noch keine Zustimmung',text:'Im Schmuckauftritt versucht Julie mehrfach, das Geschenk zurückzugeben. Die Baronin zwingt sie, es zu behalten. Sichtbares Behalten und inneres Einverständnis fallen auseinander. Auch Wendheim lässt sich nicht einfach aus dem Weg räumen.',bridge:'Lies die Reaktion auf deinen Plan als Grenze der Fremdbestimmung. Eine verschobene Spielfigur kann den Willen einer Person nicht ersetzen.',scene:'III-4',quoteKey:'command'},
 sophie:{title:'Sophie durchschaut den Plan',text:'Sophie von Hastfeld ist Rinks Mündel und Julies Vertraute. Die Baronin will Balken in einem Kasten als angebliche Schachmaschine ins Haus bringen lassen. Der Kasten soll ins Vorgemach der Schlafzimmer von Julie und der Baronin gelangen. Sophie belauscht die Intrige und erzählt Carl und Julie davon.',bridge:'Im Stück gibt Sophie die Nachricht weiter. Hier erprobst du auch Abweichungen: Deine Entscheidung legt fest, ob Carl das nötige Wissen sofort erhält.',scene:'III-8',quoteKey:'spy'},
 carl:{title:'Der vorgesehene Bräutigam hilft seinem Rivalen',text:'Carl Ruf soll nach Rinks Plan Julie heiraten. Er unterstützt jedoch Julie und Wendheim; Wendheim hat ihn früher vor Werbern gerettet. Mit Sophies Information kann Carl den ersten Kasten vor Balken besetzen und die Intrige gegen ihre Urheber wenden.',bridge:'Der Kastenwechsel folgt dem Grundzug des Stücks. Die offene Konfrontation ist eine Spielvariante. Carl handelt geschickt, aber seine Mittel sind nicht durchweg rücksichtsvoll.',scene:'IV-2',quoteKey:'substitution'},
 julie:{title:'Julie spricht selbst',text:'Am Ende vermittelt Carl zwischen den Liebenden und Rink. Rink fragt Julie schliesslich, ob sie mit Wendheim glücklich werde. Ihre eigene Antwort ist entscheidend – weder ein Schmuckgeschenk noch ein Zug eines anderen ersetzt sie.',bridge:'Hier wird aus dem Verschieben von Figuren das Ermöglichen einer eigenen Wahl. Lies Julies Antwort und stelle dann Wendheim an ihre Seite.',scene:'IV-10',quoteKey:'consent'},
 agency:{title:'Carl nennt die Menschen seine Figuren',text:'Carl ordnet die Begegnungen und führt die Beteiligten zusammen. Seine Schachsprache macht ihn zum Spielleiter. Zugleich hilft er Julie und Wendheim und übt Druck auf andere aus. Das Stück lässt sich deshalb nicht auf einen Gegensatz von guter Freiheit und böser Steuerung reduzieren.',bridge:'Begründe deine Deutung an einer konkreten Handlung oder Formulierung. Hilft Carl anderen zu handeln, bestimmt er über sie – oder verbindet sich beides?',scene:'IV-10',quoteKey:'figures'},
 book:{title:'Zurück zum Schachspiel im Drama',text:'Zu Beginn des dritten Aufzugs spielt Rink beide Seiten einer Partie und sieht vor jedem Zug ins Buch. Die Regieanweisung zeigt zunächst eine Handlung; sie sagt noch nicht, was Rink dabei versteht.',bridge:'Die beiden folgenden Züge sind unsere erfundenen Buchregeln. Von hier führt der Vergleich zur Frage, ob das korrekte Ausführen einer Regel schon Verständnis zeigt.',scene:'III-1',quoteKey:'rink'},
 outside:{title:'Ein neuer Vergleich: Searles chinesisches Zimmer',text:'John Searles Gedankenexperiment von 1980 fragt, ob das Verarbeiten von Zeichen nach Regeln bereits Verstehen ist. Eine Person beantwortet mithilfe von Regeln Eingaben in einer Sprache, die sie selbst nicht versteht.',bridge:'Das ist kein weiterer Auftritt bei Beck. Unsere erfundenen Zeichenpaare verkürzen das Gedankenexperiment auf eine Spielhandlung: Beurteile zunächst nur die von aussen sichtbare Leistung.'},
 room:{title:'Jetzt führst du die Regeln selbst aus',text:'Wie zuvor bei Rinks Buchvorgaben entscheidest du hier nicht über den Sinn der Anweisung, sondern setzt eine vorgeschriebene Zuordnung um. Die chinesischen Zeichen dienen als Spielmarken; ihre Bedeutungen werden nicht vermittelt.',bridge:'Achte darauf, welches Wissen du für die richtige Antwort tatsächlich brauchst. Die drei Zuordnungen beweisen weder Verständnis noch dessen Unmöglichkeit.',scene:'III-1'},
 inside:{title:'Aussenwirkung und eigene Erfahrung vergleichen',text:'Du hast nun selbst passende Zeichen ausgegeben. Vergleiche diese Erfahrung mit deinem Urteil als Beobachter und mit Rinks regelgeleitetem Spiel.',bridge:'Beschreibe präzise, was du gelernt hast: eine Zuordnung, eine Bedeutung oder etwas anderes. Eine offene Frage ist ebenfalls ein begründbares Ergebnis.'},
 position:{title:'Mehrere Deutungen bleiben möglich',text:'Searle unterscheidet formale Zeichenverarbeitung von Bedeutung. Die Systemantwort wendet ein, dass vielleicht nicht die einzelne ausführende Person, sondern das gesamte System versteht. Weitere Positionen betonen Wahrnehmung und Handeln.',bridge:'Entwickle deine eigene Vermutung und benenne, welche Beobachtung sie prüfen könnte. Becks Menschen als «Figuren» und «Maschinen» bieten einen Vergleich, entscheiden diese philosophische Frage aber nicht.'},
 output:{title:'Zurück zu Julie – jetzt mit einer Modellantwort',text:'Eine heutige KI soll eine konkrete Szene erklären: Balken bietet Julie Schmuck an; sie versucht ihn zurückzugeben; die Baronin befiehlt ihr, ihn zu behalten. Die Frage ist, ob man aus diesem Verhalten auf Zustimmung schliessen darf.',bridge:'Lies zuerst den Auftritt. Anschliessend erzeugst oder übernimmst du eine Antwort und prüfst sie am Text. Das Modell soll untersucht werden, nicht deine Deutung benoten.',scene:'III-4',quoteKey:'refusal'},
 audit:{title:'Der Originaltext ist dein Prüfstein',text:'Julie weist das Geschenk zurück, während die Baronin auf dem Behalten besteht. Eine flüssige Erklärung kann diese Unterscheidung übergehen oder ein Motiv erfinden, das die Passage nicht belegt.',bridge:'Vergleiche Sprache, Zitat und Schlussfolgerung der Antwort mit dem Auftritt. Formuliere dann deinen eigenen Befund.',scene:'III-4',quoteKey:'command'},
 network:{title:'Die vier Stationen sind nicht dieselbe Maschine',text:'Beim historischen Automaten wählt ein verborgener Mensch den Zug. Bei Beck werden Menschen in soziale Pläne eingespannt und widersetzen sich ihnen. Im Zimmer steht Regelbefolgung zur Debatte. Ein heutiges Sprachmodell erzeugt seine Ausgabe durch Berechnung.',bridge:'Untersuche Daten, Training und Inferenz getrennt. Gemeinsame Bilder wie Brett und Kasten machen Unterschiede vergleichbar; sie heben sie nicht auf.'},
 final:{title:'Was trägt der Vergleich für dich?',text:'Du hast eine sichtbare Leistung, ihre Ursachen, fremde Pläne und eigene Entscheidungen untersucht. Nun kehrst du zu deiner ersten Zuschreibung von Intelligenz zurück.',bridge:'Beziehe dich auf mindestens eine Handlung oder Textstelle aus Beck und eine Beobachtung aus dem Zimmer oder der Antwortprüfung. Erkläre, was dein Kriterium verändert hat oder warum du daran festhältst.',scene:'IV-10'},
 ending:{title:'Deine Lektüre und deine Zugspur',text:'Das Ende ist kein Lösungsschlüssel. Deine Texte halten fest, wie du Beobachtungen, Deutungen und offene Fragen verbunden hast.',bridge:'Vergleicht eure stärksten Textbelege. Welche Unterschiede zwischen Mensch, Spielfigur und Maschine bleiben bestehen? Im Lesefenster kannst du die betreffenden Auftritte nochmals nachlesen.',scene:'IV-10'}
};
export function createReading(){
 const dialog=node('dialog',undefined,'reading-dialog');dialog.id='reading-dialog';dialog.setAttribute('aria-label','Becks Stück lesen');document.body.append(dialog);
 const close=node('button','× Schliessen','close');close.type='button';close.onclick=()=>dialog.close();dialog.append(close,node('h2','Heinrich Beck · Die Schachmaschine'),node('p','Lustspiel in vier Aufzügen · Berlin, 1798. Arbeitsgrundlage: das bereitgestellte Transkript. Die Lesefassung berichtigt offensichtliche Übertragungsfehler und bewahrt historische Schreibweisen. Kurze Zusammenfassungen erklären die Abschnitte in heutigem Deutsch; das Ausgangstranskript bleibt zugänglich.','source-note'));
 const cast=node('details');cast.append(node('summary','Wer ist wer? · Figuren und Beziehungen'));for(const c of characters)cast.append(node('h3',c.name),node('p',c.text));dialog.append(cast);
 const label=node('label','Auftritt lesen');label.htmlFor='reading-scene';const select=node('select');select.id='reading-scene';for(const s of scenes){const option=node('option',s.title);option.value=s.id;select.append(option);}dialog.append(label,select);const text=node('div',undefined,'play-text');text.tabIndex=0;dialog.append(text);
 const link=node('a','Vollständige korrigierte Lesefassung öffnen ↗');link.href=import.meta.env.BASE_URL+'sources/beck-1798-lesefassung.txt';link.target='_blank';link.rel='noopener';dialog.append(link);
 function render(){text.replaceChildren();const scene=scenes.find(s=>s.id===select.value);text.append(node('h3',scene.title));for(const page of passagePages(scene.text))text.append(editionGuide(page));for(const line of correctPassage(scene.text).split('\n').filter(Boolean))text.append(node('p',line));}
 select.onchange=render;
 return {open(id='III-1'){select.value=scenes.some(s=>s.id===id)?id:'III-1';render();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}};
}
export function addContext(parent,id,reader,quotes){const c=contexts[id];if(!c)return;const box=node('section',undefined,'reading-context');box.append(node('p',c.title,'eyebrow'),node('p',c.text));for(const key of (['baronin','resistance','output','audit'].includes(id)?['refusal','command']:c.quoteKey?[c.quoteKey]:[])){const q=quotes[key];box.append(node('blockquote','«'+correctPassage(q.quote)+'»'),node('p',q.speaker+' · '+q.location,'source-note'));}box.append(node('p',c.bridge,'reading-bridge'));if(c.scene){const b=node('button','Auftritt im Zusammenhang lesen ↗','quiet');b.type='button';b.onclick=()=>reader.open(c.scene);box.append(b);}parent.append(box);}
