import {lookupWord,dictionaryUrl} from './glossary.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
export function createReadingHelp({reader,onSpeaker}){
 const bar=el('div',null,'reading-help');bar.hidden=true;reader.querySelector('#scene-controls').before(bar);
 const explain=el('button','Wort erklären');explain.id='explain-word';explain.type='button';bar.append(explain);
 const label=el('span','KI-Lesung','audio-label');bar.append(label);
 const audio=el('audio');audio.controls=true;audio.preload='none';audio.setAttribute('aria-label','Aktuellen Textabschnitt vorlesen');bar.append(audio);
 const followLabel=el('label',null,'audio-follow'),follow=el('input');follow.type='checkbox';follow.checked=true;followLabel.append(follow,document.createTextNode('Text mitführen'));bar.append(followLabel);
 const info=el('button','Zur Lesung');info.type='button';bar.append(info);
 const status=el('span','','audio-status');status.setAttribute('role','status');bar.append(status);
 const dialog=el('dialog',null,'word-dialog');dialog.setAttribute('aria-labelledby','word-heading');document.body.append(dialog);
 const heading=el('h2','Wort erklären');heading.id='word-heading';const close=el('button','Schliessen');close.type='button';close.onclick=()=>dialog.close();
 const form=el('form'),inputLabel=el('label','Wort aus dem Text'),input=el('input');input.id='word-query';input.maxLength=80;input.autocomplete='off';inputLabel.htmlFor=input.id;const submit=el('button','Erklären');submit.type='submit';form.append(inputLabel,input,submit);
 const result=el('div');result.setAttribute('aria-live','polite');const instructions=el('p','Unterstrichene Wörter anklicken. Oder ein Wort markieren und „Wort erklären“ wählen. Du kannst auch selbst ein Wort eingeben.');dialog.append(close,heading,instructions,form,result);
 let stage=null,article=null,manifest=null,track=null,key=null,lastCue=-1,previousFocus=null;
 const manifestReady=fetch(import.meta.env.BASE_URL+'audio/manifest.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(m=>{manifest=m;loadTrack();}).catch(()=>{manifest={pages:{}};loadTrack();});
 function show(word=''){heading.textContent='Wort erklären';form.hidden=false;instructions.hidden=false;audio.pause();previousFocus=document.activeElement;input.value=word.slice(0,80);renderWord();if(!dialog.open)dialog.showModal();input.focus();input.select();}
 function renderWord(){result.replaceChildren();const word=input.value.trim();if(!word)return;const entry=lookupWord(word);result.append(el('h3',entry?.word||word));if(entry){result.append(el('p',entry.meaning));if(entry.context)result.append(el('h4','Im Stück · Lesehinweis'),el('p',entry.context));result.append(el('small','Redaktionelle Lesehilfe. Eine Deutung des Zusammenhangs ist keine feststehende Figurenabsicht.'));}else{result.append(el('p','Für dieses Wort ist noch keine redaktionelle Erklärung hinterlegt. Im Wörterbuch kannst du die Bedeutung und mögliche heutige Schreibweisen nachschlagen. Bei ungewöhnlichen Formen kann auch ein Übertragungsfehler vorliegen.'));}const link=el('a',entry?.word==='Kaprize'?'Wortbedeutung im Duden':'Im DWDS nachschlagen ↗');link.href=entry?.word==='Kaprize'?'https://www.duden.de/rechtschreibung/Caprice':dictionaryUrl(entry?.word||word);link.target='_blank';link.rel='noopener noreferrer';const source=el('p');source.append(link);result.append(source);if(stage?.text){const term=word.toLowerCase(),at=stage.text.toLowerCase().indexOf(term);if(at>=0){result.append(el('h4','Textumgebung'),el('blockquote',stage.text.slice(Math.max(0,at-110),Math.min(stage.text.length,at+word.length+180))));}}}
 form.onsubmit=e=>{e.preventDefault();renderWord();};dialog.addEventListener('close',()=>{previousFocus?.isConnected&&previousFocus.focus();});
 explain.onpointerdown=e=>e.preventDefault();explain.onclick=()=>{const selection=window.getSelection();const selected=selection?.rangeCount&&article?.contains(selection.anchorNode)?selection.toString().trim():'';show(selected.length<=80?selected:'');};
 info.onclick=()=>{heading.textContent='Zur Lesung';form.hidden=true;instructions.hidden=true;audio.pause();previousFocus=info;input.value='';result.replaceChildren(el('h3','Eine vorbereitete KI-Lesung'),el('p','Derzeit sind '+Object.keys(manifest?.pages||{}).length+' von 79 Textabschnitten vertont. Die restlichen Aufnahmen fehlen noch; das kostenlose Sprachkontingent ist ausgeschöpft.'),el('p','Die deutsche Stimme „Nero – Thoughtful & Clear“ wird mit HeyGen erzeugt. Sprecherbezeichnungen und Regieanweisungen werden mitgelesen; zusätzliche Pausen gliedern die Redewechsel. Es handelt sich nicht um eine menschliche Aufnahme oder eine abschliessend schauspielerisch redigierte Interpretation.'),el('p','Der vollständige Transkripttext bleibt erhalten, einschliesslich historischer Schreibweisen und möglicher Übertragungsfehler. Einzelne Aussprachen und Betonungen können deshalb unpassend sein. Die Stimme legt keine verbindliche Interpretation fest.'),el('p','Die Tondateien werden von dieser Website geladen. Deine Notizen und Deutungen werden nicht an einen Sprachdienst geschickt. Vorlesen startet nur auf deinen Wunsch und endet am Abschnittsende.'));if(!dialog.open)dialog.showModal();close.focus();};
 function loadTrack(){if(!stage)return;if(manifest)label.textContent='KI-Lesung · '+Object.keys(manifest.pages).length+' von 79 Abschnitten';track=manifest?.pages?.[stage.id]||null;if(track){const src=import.meta.env.BASE_URL+track.file;if(audio.getAttribute('src')!==src){audio.src=src;lastCue=-1;}status.textContent='';audio.hidden=false;followLabel.hidden=false;}else{audio.hidden=true;followLabel.hidden=true;status.textContent=manifest?'Für diesen Abschnitt liegt noch keine Lesung vor.':'Lesung wird geladen …';}}
 function stop(){audio.pause();if(audio.readyState)audio.currentTime=0;lastCue=-1;article?.querySelectorAll('.audio-current').forEach(n=>n.classList.remove('audio-current'));}
 audio.addEventListener('error',()=>{status.textContent='Die Tondatei konnte nicht geladen werden. Bitte die Seite neu laden oder später erneut versuchen.';});
 function syncCue(){if(!track||!article||audio.paused)return;const i=track.cues.findIndex((c,i)=>audio.currentTime>=c.time&&(i===track.cues.length-1||audio.currentTime<track.cues[i+1].time));if(i<0||i===lastCue)return;lastCue=i;const cue=track.cues[i];article.querySelectorAll('.speech-turn').forEach(n=>n.classList.toggle('audio-current',Number(n.dataset.start)===cue.start));onSpeaker(cue.speaker);const current=article.querySelector('.audio-current');if(follow.checked&&current){const scroller=reader.querySelector('#scene-controls');scroller.scrollTop+=current.getBoundingClientRect().top-scroller.getBoundingClientRect().top-16;}}
 audio.addEventListener('timeupdate',syncCue);
 audio.addEventListener('ended',()=>{article?.querySelectorAll('.audio-current').forEach(n=>n.classList.remove('audio-current'));status.textContent='Abschnitt zu Ende. Du bestimmst, wann es weitergeht.';});
 function annotate(node){article=node;if(!node)return;const walker=document.createTreeWalker(node,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const text of nodes){const fragments=document.createDocumentFragment();let end=0;for(const match of text.textContent.matchAll(/[\p{L}]+/gu)){if(!lookupWord(match[0]))continue;fragments.append(document.createTextNode(text.textContent.slice(end,match.index)));const b=el('button',match[0],'glossary-word');b.type='button';b.dataset.word=match[0];b.title=match[0]+' erklären';b.setAttribute('aria-label',match[0]+' — Wort erklären');b.onclick=e=>{e.stopPropagation();show(match[0]);};b.onkeydown=e=>e.stopPropagation();fragments.append(b);end=match.index+match[0].length;}if(end){fragments.append(document.createTextNode(text.textContent.slice(end)));text.replaceWith(fragments);}}}
 function mount(next,node){if(next.id!==key||!node){stop();key=next.id;audio.removeAttribute('src');audio.load();}stage=next;article=node;bar.hidden=!node;if(node){annotate(node);loadTrack();lastCue=-1;syncCue();}}
 function hide(){stop();stage=null;key=null;bar.hidden=true;if(dialog.open)dialog.close();}
 return {mount,hide,isPlaying:()=>!audio.paused,ready:manifestReady};
}
