import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {squarePosition} from './logic.js';
export function createScene(container,onSquare){
 const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x151713,.027);
 const camera=new THREE.PerspectiveCamera(37,1,.1,100); camera.position.set(10,12,14);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.setClearColor(0x151713,0); container.append(renderer.domElement);
 const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.minDistance=2.5;controls.maxDistance=55;controls.zoomSpeed=1.15;controls.maxPolarAngle=Math.PI*.47;controls.target.set(0,0,0);controls.enablePan=true;
 const referenceDistance=21;
 function getZoom(){return referenceDistance/camera.position.distanceTo(controls.target)*100;}
 function publishCamera(){container.dataset.cameraDistance=camera.position.distanceTo(controls.target).toFixed(5);container.dataset.cameraTarget=controls.target.toArray().join(',');container.dataset.cameraPosition=camera.position.toArray().join(',');container.dispatchEvent(new CustomEvent('boardzoom',{detail:getZoom()}));}
 function setDistance(distance){const delta=camera.position.clone().sub(controls.target).normalize().multiplyScalar(Math.max(controls.minDistance,Math.min(controls.maxDistance,distance)));camera.position.copy(controls.target).add(delta);controls.update();publishCamera();}
 function setZoom(percent){if(Number.isFinite(percent)&&percent>0)setDistance(referenceDistance/(percent/100));}
 function orient(position,target=new THREE.Vector3()){const distance=camera.position.distanceTo(controls.target);const damping=controls.enableDamping;controls.enableDamping=false;controls.update();const direction=position.clone().sub(target).normalize();controls.target.copy(target);camera.position.copy(target).addScaledVector(direction,distance);controls.update();controls.enableDamping=damping;publishCamera();}
 controls.addEventListener('change',publishCamera);publishCamera();
 scene.add(new THREE.HemisphereLight(0xffeed2,0x18212a,2.2)); const key=new THREE.DirectionalLight(0xffdeab,3.3);key.position.set(-4,12,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-9;key.shadow.camera.right=9;key.shadow.camera.top=9;key.shadow.camera.bottom=-9;scene.add(key);
 const rim=new THREE.PointLight(0xc0cddd,35);rim.position.set(5,4,-6);scene.add(rim);
 const board=new THREE.Group();scene.add(board);const tiles=[],pieces=new THREE.Group(),under=new THREE.Group(),layers=new THREE.Group();scene.add(pieces,under,layers);
 const materials={light:new THREE.MeshStandardMaterial({color:0xb8a27d,roughness:.72}),dark:new THREE.MeshStandardMaterial({color:0x36362b,roughness:.67}),brass:new THREE.MeshStandardMaterial({color:0xa18248,metalness:.78,roughness:.3}),black:new THREE.MeshStandardMaterial({color:0x242721,metalness:.28,roughness:.4}),white:new THREE.MeshStandardMaterial({color:0xe7d7b7,roughness:.37})};
 function box(w,h,d,mat,x=0,y=0,z=0,parent=board){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 const base=box(8.65,.65,8.65,materials.black,0,-.55);box(8.78,.07,8.78,materials.brass,0,-.2);
 for(let rank=1;rank<=8;rank++)for(let f=0;f<8;f++){const square=String.fromCharCode(97+f)+rank;const p=squarePosition(square);const t=box(.99,.16,.99,(rank+f)%2?materials.dark:materials.light,p.x,0,p.z);t.userData.square=square;tiles.push(t);}
 function label(text,size=1,color='#d7c4a2'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font='42px Georgia';ctx.textAlign='center';ctx.fillText(text,256,78,490);const texture=new THREE.CanvasTexture(c);const m=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false});const s=new THREE.Sprite(m);s.scale.set(size,size/4,1);return s;}
 for(let i=0;i<8;i++){const a=label('abcdefgh'[i],.45);a.position.set(i-3.5,.12,4.3);board.add(a);const b=label(String(i+1),.45);b.position.set(-4.3,.12,3.5-i);board.add(b);}
 const ring=new THREE.Mesh(new THREE.RingGeometry(.32,.43,48),new THREE.MeshBasicMaterial({color:0xf0cb7c,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.1;ring.visible=false;scene.add(ring);
 function clear(group){while(group.children.length){const child=group.children[0];group.remove(child);child.traverse(o=>{o.geometry?.dispose();if(o.material&&!Object.values(materials).includes(o.material)){o.material.map?.dispose();o.material.dispose();}});}}
 function piece(type,color,square,title){const g=new THREE.Group();const mat=color==='w'?materials.white:materials.black;
 const profile=[new THREE.Vector2(0,0),new THREE.Vector2(.27,0),new THREE.Vector2(.29,.08),new THREE.Vector2(.23,.15),new THREE.Vector2(.14,.2),new THREE.Vector2(.10,.43),new THREE.Vector2(.19,.48),new THREE.Vector2(.14,.54)];
 const body=new THREE.Mesh(new THREE.LatheGeometry(profile,28),mat);g.add(body);const head=new THREE.Mesh(type==='r'?new THREE.BoxGeometry(.34,.24,.34):type==='n'?new THREE.ConeGeometry(.2,.43,4):new THREE.SphereGeometry(type==='p'?.16:.2,20,16),mat);head.position.y=type==='n'?.72:.66;g.add(head);
 if(type==='k'){box(.09,.3,.09,mat,0,.97,0,g);box(.28,.08,.09,mat,0,1.02,0,g);}if(type==='q'){const crown=new THREE.Mesh(new THREE.TorusGeometry(.15,.035,8,20),materials.brass);crown.rotation.x=Math.PI/2;crown.position.y=.85;g.add(crown);}
 g.traverse(o=>{o.castShadow=true;o.userData.square=square;});const p=squarePosition(square);g.position.set(p.x,.09,p.z);g.userData.square=square;if(title){const t=label(title,2.3);t.position.y=1.25;g.add(t);}pieces.add(g);return g;}
 let speaking=null;const speakerHalo=new THREE.Mesh(new THREE.RingGeometry(.46,.55,48),new THREE.MeshBasicMaterial({color:0xaeeaff,side:THREE.DoubleSide}));speakerHalo.rotation.x=-Math.PI/2;speakerHalo.visible=false;scene.add(speakerHalo);let cast=[];function speaker(name){speaking=name;const found=cast.find(p=>p.label===name);speakerHalo.visible=!!found;if(found){const p=squarePosition(found.square);speakerHalo.position.set(p.x,.19,p.z);}}
 function setPieces(items){cast=items;clear(pieces);for(const p of items)piece(p.type||'p',p.color||'w',p.square,p.label);speaker(speaking);}
 const relations=new THREE.Group();scene.add(relations);
 function showRelations(edges,positions){clear(relations);for(const [i,e]of edges.entries()){const a=positions.get(e.from),b=positions.get(e.to);if(!a||!b)continue;const p=squarePosition(a),q=squarePosition(b);const y=.28+(i%5)*.09;const start=new THREE.Vector3(p.x,y,p.z),end=new THREE.Vector3(q.x,y,q.z);const direction=end.clone().sub(start).normalize(),length=start.distanceTo(end);const color={knowledge:0x8ecde6,intention:0xf0c779,assumption:0xd8a5db,dependence:0xed9e88,position:0xa9d39b}[e.layer];const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([start,end]),e.certainty==='explicit'?new THREE.LineBasicMaterial({color}):new THREE.LineDashedMaterial({color,dashSize:.16,gapSize:.1,transparent:true,opacity:e.certainty==='unknown'?.45:.9}));line.computeLineDistances();relations.add(line);const head=new THREE.Mesh(new THREE.ConeGeometry(.11,.3,8),new THREE.MeshBasicMaterial({color}));head.position.copy(end.clone().addScaledVector(direction,-.4));head.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),direction);relations.add(head);if(['control','release'].includes(e.effect)){const ring=new THREE.Mesh(new THREE.RingGeometry(e.effect==='control'?.46:.3,e.effect==='control'?.52:.37, e.effect==='control'?4:40),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(q.x,.16,q.z);relations.add(ring);}}}
 const props=new THREE.Group();scene.add(props);
 const automaton=new THREE.Group();props.add(automaton);automaton.position.set(0,0,-5.5);
 box(1.1,1.7,.7,materials.dark,0,.4,0,automaton);box(1.6,.2,1,materials.black,0,-.55,0,automaton);
 const face=new THREE.Mesh(new THREE.SphereGeometry(.37,24,20),materials.white);face.position.y=1.55;automaton.add(face);
 const turban=new THREE.Mesh(new THREE.SphereGeometry(.46,24,16),materials.brass);turban.scale.y=.62;turban.position.y=1.85;automaton.add(turban);
 for(const x of [-.72,.72]){box(.23,.23,1.5,materials.dark,x,.8,.55,automaton);box(.25,.14,.3,materials.white,x,.8,1.35,automaton);}
 const room=new THREE.Group();props.add(room);room.position.set(.5,.1,-3.5);box(1.6,2,1.5,materials.black,0,1,0,room);box(.9,.04,.04,materials.brass,0,.7,.76,room);room.visible=false;
 function setTheme(i){automaton.visible=i===0;room.visible=i===2||i===3;room.scale.setScalar(i===2?1:.7);const palettes=[[0xb8a27d,0x36362b],[0xae9280,0x4a282b],[0xb6c9bc,0x354644],[0x718899,0x192c39]];materials.light.color.setHex(palettes[i][0]);materials.dark.color.setHex(palettes[i][1]);}
 // Schematic cutaway: a hidden operator, gears and shafts beneath the board.
 for(let i=0;i<7;i++){const gear=new THREE.Mesh(new THREE.TorusGeometry(.38+(i%2)*.14,.09,8,16),materials.brass);gear.rotation.x=Math.PI/2;gear.position.set((i%4)*1.5-2.3,-1,(Math.floor(i/4))*2-1);under.add(gear);for(let j=0;j<12;j++)box(.13,.16,.13,materials.brass,gear.position.x+Math.cos(j*Math.PI/6)*.47,-1,gear.position.z+Math.sin(j*Math.PI/6)*.47,under);}
 box(.5,.6,.5,materials.black,0,-1.35,1,under);const head=new THREE.Mesh(new THREE.SphereGeometry(.23),materials.white);head.position.set(0,-.83,1);under.add(head);for(const x of [-.4,.4])box(.13,.13,.9,materials.brass,x,-1.1,.7,under);
 under.visible=false;let opened=false,era=0;
 function open(value,index=era){opened=value;era=index;under.visible=value&&index===0;}
 function showLayers(enabled){clear(layers);enabled.forEach((yes,i)=>{if(!yes)return;const mat=new THREE.MeshBasicMaterial({color:[0xc6a778,0xba6d78,0x9dc9b4,0x7bb7ec][i],transparent:true,opacity:.12,side:THREE.DoubleSide,depthWrite:false});const plane=new THREE.Mesh(new THREE.PlaneGeometry(8,8),mat);plane.rotation.x=-Math.PI/2;plane.position.y=.7+i*.8;layers.add(plane);const grid=new THREE.GridHelper(8,8,[0xc6a778,0xba6d78,0x9dc9b4,0x7bb7ec][i],0x637373);grid.position.y=plane.position.y;layers.add(grid);const text=label(['1770 · MECHANIK','1798 · FIGUR','1980 · ZEICHEN','2026 · TOKEN'][i],3);text.position.set(0,plane.position.y+.15,-4);layers.add(text);});}
 function mark(square){ring.visible=!!square;if(square){const p=squarePosition(square);ring.position.set(p.x,.13,p.z);}}
 const ray=new THREE.Raycaster();let down;
 renderer.domElement.addEventListener('pointerdown',e=>down=e.button===0?{x:e.clientX,y:e.clientY}:null);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObjects([...tiles,...pieces.children],true);const hit=hits.find(h=>h.object.userData.square);if(hit)onSquare(hit.object.userData.square);});
 const resize=new ResizeObserver(()=>{const {width,height}=container.getBoundingClientRect();camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height);});resize.observe(container);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;renderer.setAnimationLoop(()=>{const factor=reduced?1:.08;tiles.forEach((t,i)=>{const lift=opened&&i>=32?2.6:0;t.position.y+=(lift-t.position.y)*factor;});base.position.y+=((opened?-1.8:-.55)-base.position.y)*factor;controls.update();renderer.render(scene,camera);});
 return {getZoom,setZoom,resetZoom(){setDistance(referenceDistance);},speaker,viewRelationship(square,targets=[]){const p=squarePosition(square);const centre=targets.length?targets.map(squarePosition).reduce((a,b)=>({x:a.x+b.x/targets.length,z:a.z+b.z/targets.length}),{x:0,z:0}):{x:0,z:0};const back=new THREE.Vector3(p.x-centre.x,0,p.z-centre.z);if(back.length()<.5)back.set(0,0,1);back.normalize().multiplyScalar(7.5);orient(new THREE.Vector3(p.x+back.x,7,p.z+back.z),new THREE.Vector3(centre.x*.35,0,centre.z*.35));},showRelations,clearRelations(){clear(relations);},viewFrom(square){const p=squarePosition(square);const v=new THREE.Vector3(p.x,0,p.z);if(v.length()<1)v.set(0,0,1);v.normalize().multiplyScalar(13);orient(new THREE.Vector3(v.x,7,v.z));},setPieces,setTheme,open,showLayers,mark,view(mode){orient(new THREE.Vector3(...(mode==='top'?[0,20,.01]:mode==='inside'?[0,2.5,13]:mode==='opponent'?[0,10,-16]:mode==='left'?[-16,9,0]:mode==='right'?[16,9,0]:mode==='close'?[7,6,9]:[10,12,14])));},dispose(){renderer.setAnimationLoop(null);resize.disconnect();controls.dispose();renderer.dispose();}};
}
