import {createDecisionUI} from './decision-ui.js';
import {pages,roles} from './play-state.js';
import {profilesAt,perspectiveFacts,readingLimit} from './inner-perspectives.js';
import {quote,location} from './dramaturgy.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(p,text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;p.append(b);return b;};
export const theories=[
 {id:'automaton',title:'1770 · Schachautomat: Wer handelt hinter dem sichtbaren Zug?',text:'Kempelens Automat erweckte den Eindruck selbsttätigen Schachspiels. Tatsächlich lenkte ein verborgener Mensch die Figur. Die Zuschreibung einer Leistung an die sichtbare Maschine verdeckte ihren menschlichen Urheber.',bridge:'Vergleiche im bereits gelesenen Stück sichtbare Handlung, verborgene Ausführung und geglaubte Identität. Becks Kastenhandlung ist eine literarische Intrige und keine technische Beschreibung des historischen Automaten.',limit:'Der historische Betrug beweist weder, dass Maschinen grundsätzlich nicht denken können, noch, dass hinter heutigen KI-Antworten ein Mensch sitzt, der jede Antwort eingibt.',source:'https://blog.hnf.de/250-jahre-schachtuerken/',sourceTitle:'Heinz Nixdorf MuseumsForum: 250 Jahre Schachtürke'},
 {id:'turing',title:'1950 · Turing-Test: Was lässt sich aus Antworten erschliessen?',text:'Turing schlägt das Imitationsspiel als Zugang zur Frage nach maschineller Intelligenz vor. In der geläufigen Mensch-Maschine-Fassung versucht eine fragende Person, anhand schriftlicher Antworten die verborgenen Gesprächspartner zu unterscheiden.',bridge:'Formuliere eine Rückfrage, die zwischen blosser Rollenbehauptung und situationsbezogenem Wissen unterscheiden könnte. Prüfe bei einer Figur, welchen Eindruck sie erzeugen will und welche Beobachtung ihn widerlegen könnte.',limit:'Eine überzeugende Antwort entscheidet für sich allein weder über Bewusstsein noch über echtes Verstehen. Eine Rollenverwechslung im Stück ist kein bestandener Turing-Test.',source:'https://courses.cs.umbc.edu/471/papers/turing.html',sourceTitle:'Alan Turing: Computing Machinery and Intelligence (1950)'},
 {id:'room',title:'1980 · Chinesisches Zimmer: Regeln anwenden oder Bedeutung verstehen?',text:'Searle beschreibt eine Person, die chinesische Zeichen nach Regeln verarbeitet, ohne Chinesisch zu verstehen. Er bestreitet, dass das Ausführen eines Programms allein bereits Verstehen begründet. Die Systemantwort hält dagegen: Entscheidend könnte das gesamte System sein, nicht die einzelne ausführende Person.',bridge:'Unterscheide im Stück das Befolgen eines Auftrags, das Verstehen seiner Bedeutung und das Durchschauen der Absicht dahinter. Welcher Akteur kennt welches Teilstück des Plans? Kann das Zusammenwirken mehr leisten als das Wissen eines Einzelnen?',limit:'Das Gedankenexperiment ist eine Kritik an starker KI, keine technische Vorstufe der KI und kein allgemein akzeptierter Beweis ihrer Unmöglichkeit. Menschliche Figuren dürfen nicht einfach mit bedeutungslosen Symbolverarbeitern gleichgesetzt werden.',source:'https://plato.stanford.edu/entries/chinese-room/',sourceTitle:'Stanford Encyclopedia of Philosophy: The Chinese Room Argument'},
 {id:'ai',title:'Heutige KI · Eine Antwort und ihre überprüfbaren Voraussetzungen',text:'Für ein späteres Figurenmodell können wir Informationen, angenommene Ziele, verfügbare Handlungen und Zustandsänderungen ausdrücklich modellieren. Ein Sprachmodell könnte Vorschläge formulieren; Regeln prüfen, welche Informationen und Handlungen zulässig sind.',bridge:'Zeige neben der Äusserung: bereitgestellte Textbelege, bekannte und offene Tatsachen, Alternativen, ausgewählte Handlung und Folgen für andere Figuren. Verändere einen Eingang und vergleiche das Ergebnis.',limit:'Dies wäre ein von uns konstruiertes Modell der Figur. Ein nachträglich formulierter innerer Monolog ist kein verlässliches Protokoll interner Modellberechnungen. Beobachtbare Verarbeitungsschritte müssen tatsächlich von der Anwendung erfasst werden.',source:null}
];
export function createStrategyLab({onSource,onPerspective}){
 const decision=createDecisionUI({onSource});
 const openButton=el('button','Innenperspektiven · Denkmodelle');openButton.type='button';openButton.id='strategy-open';
 const dialog=el('dialog',null,'strategy-dialog');dialog.setAttribute('aria-labelledby','strategy-heading');document.body.append(dialog);
 let current=null,perspective=0,signature='',returnFocus=null;const storageKey='schachmaschine-strategy-notes-v1';let notes={};try{const parsed=JSON.parse(localStorage.getItem(storageKey)||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))notes=parsed;}catch{}
 function key(suffix){return `${current.room?.code||'solo'}:${current.room?.epoch||0}:${current.stage.id}:${perspective}:${suffix}`;}
 function addNote(parent,label,suffix,placeholder=''){const wrap=el('label',label),area=el('textarea');area.rows=3;area.maxLength=2000;area.placeholder=placeholder;const k=key(suffix);area.value=typeof notes[k]==='string'?notes[k]:'';area.dataset.strategyNote=suffix;const status=el('small','Privat auf diesem Gerät gespeichert.');area.oninput=()=>{notes[k]=area.value;try{localStorage.setItem(storageKey,JSON.stringify(notes));status.textContent='Privat auf diesem Gerät gespeichert.';}catch{status.textContent='Gerätespeicher nicht verfügbar: bitte Notizen als Datei sichern.';}};wrap.append(area);parent.append(wrap,status);}
 function evidence(parent,f){const card=el('article',null,'strategy-evidence');card.append(el('p',f.label||'Originalbeleg'),el('blockquote',quote(f)),el('small',location(f)));button(card,'Beleg im Zusammenhang',()=>onSource(f.page,f.start,f.end));parent.append(card);}
 function render(){if(!current)return;dialog.replaceChildren();button(dialog,'Schliessen',()=>dialog.close()).className='strategy-close';dialog.append(el('h2','Innenperspektiven und strategisches Handeln'));dialog.querySelector('h2').id='strategy-heading';dialog.append(el('p','Hier rekonstruierst du eine mögliche Innensicht aus dem gelesenen Text. Fragen und Lesarten sind keine behaupteten Gedanken der Figuren. Deine privaten Entwürfe ersetzen die belegten Beziehungen in der Werkstatt nicht.'));
 const choose=el('select');choose.id='inner-role';choose.setAttribute('aria-label','Figur im Denklabor');for(let i=0;i<roles.length;i++){const o=el('option',i?roles[i].name:'Publikum / Regie');o.value=i;choose.append(o);}choose.value=perspective;choose.onchange=()=>onPerspective(Number(choose.value));dialog.append(choose);
 decision.button(dialog,current,perspective);
 const inner=el('section');inner.id='inner-study';dialog.append(inner);inner.append(el('h3',perspective?roles[perspective].name+' · Was könnte diese Figur annehmen?':'Publikum · Mehrwissen und Zuschreibung'));
 const profiles=profilesAt(perspective,current.stage,current.state.opened);if(perspective&&!profiles.length)inner.append(el('p','Für diese Figur ist bis zu deiner geöffneten Textstrecke noch kein redaktioneller Innenperspektiv-Beleg erreicht. Erfinde kein Vorwissen. Du kannst eigene Beobachtungen mit einem bereits gelesenen Beleg in der Werkstatt festhalten.'));
 for(const profile of profiles){const section=el('section',null,'inner-profile');section.dataset.profile=profile.name;section.append(el('h4',profile.name));const index=pages.findIndex(p=>p.id===profile.page);evidence(section,{page:index,start:profile.start,end:profile.start+profile.needle.length,label:'Ausgangspunkt, keine abschliessende Charakterisierung'});for(const [title,text]of [['Ziel und möglicher Zielkonflikt',profile.goal],['Mittel und strategischer Zug',profile.tactic],['Modell des Gegenübers',profile.other],['Fehlannahme / mögliche Kosten',profile.risk],['Alternative und Gegenprobe',profile.alternative]])section.append(el('h5',title),el('p',text));inner.append(section);}
 const facts=perspectiveFacts(perspective,current.stage,current.state.opened);const known=el('details');known.append(el('summary',`Belegter Zugang dieser Perspektive · ${facts.filter(f=>f.known).length}`));for(const f of facts.filter(f=>f.known)){evidence(known,f);if(f.disclosure)known.append(el('p','Erst durch die spätere Enthüllung für diese Figur belegt: '+location(f.disclosure)));}inner.append(known);
 if(perspective){const unknown=el('details');unknown.append(el('summary','Mehrwissen des Publikums / Zugang der Figur nicht gesichert'));unknown.append(el('p','Fehlender Beleg für Zugang bedeutet nicht nachgewiesenes Nichtwissen. Anwesenheit beweist nicht, dass alles gehört wurde.'));for(const f of facts.filter(f=>!f.known))evidence(unknown,f);inner.append(unknown);}else inner.append(el('p','Unterscheide, was du auf der Bühne siehst, von dem, was eine Figur wahrnehmen kann. Eine Täuschung kann dem Publikum bekannt sein und dennoch innerhalb der Handlung funktionieren.'));
 const draft=el('details');draft.id='inner-draft';draft.append(el('summary','Meine Rekonstruktion der Innenperspektive'));for(const [id,label,placeholder]of [
 ['knowledge','1 · Belegtes Wissen','Die Figur konnte … erfahren. Beleg: …'],['belief','2 · Vermutung und Irrtum','Sie könnte glauben, dass … Offen bleibt …'],['goal','3 · Ziel und Zielkonflikt','Sie will …; gleichzeitig müsste sie …'],['other','4 · Vermutetes Wissen des Gegenübers','Sie erwartet, dass … über … glaubt …'],['move','5 · Handlung und erhoffte Reaktion','Wenn sie … tut, soll … daraufhin …'],['cost','6 · Risiko, Gegenwehr und Alternative','Der Plan könnte an … scheitern. Eine Alternative wäre …'],['revision','7 · Gegenbeleg / Revision','Seit der Stelle … muss ich meine Annahme … ändern.']])addNote(draft,label,id,placeholder);inner.append(draft);
 const theory=el('section');theory.id='thinking-models';theory.append(el('h3','Täuschung, Regel und Intelligenzzuschreibung'),el('p','1770 → 1798 → 1950 → 1980 → heutige KI: eine Vergleichsfolge, keine geradlinige technische Entwicklung. Die folgenden Bezüge sind heutige Interpretationsangebote.'));
 for(const item of theories){const d=el('details');d.dataset.theory=item.id;d.append(el('summary',item.title),el('p',item.text),el('h4','Am bereits gelesenen Text prüfen'),el('p',item.bridge),el('h4','Grenze des Vergleichs'),el('p',item.limit));if(item.source){const a=el('a',item.sourceTitle+' ↗');a.href=item.source;a.target='_blank';a.rel='noopener noreferrer';d.append(a);}addNote(d,'Meine Verbindung zur Figur mit Textbeleg','theory-'+item.id);theory.append(d);}dialog.append(theory);
 const turing=el('details');turing.id='turing-lab';turing.append(el('summary','Turing-Werkstatt · einen Blindvergleich entwerfen'),el('p','Arbeitsanordnung für eure Gruppe: Eine Person stellt schriftliche Fragen. Zwei verdeckte Antwortgeber antworten über eine Vermittlung. Legt vorher fest, was verglichen wird: Mensch und Computer oder zwei gespielte Figurenrollen. Identitäten und Herkunft erst nach dem begründeten Urteil offenlegen. Hier läuft kein echter KI-Test; ihr protokolliert euren Versuch.'),el('p','Ohne KI-Zugang könnt ihr Rollenantwort und starre Antwortregel vergleichen. Nennt das einen Regelvergleich, keinen bestandenen Turing-Test. Gleiche Bedingungen, Rückfragen und Gegenbeispiele sind wichtiger als ein blosses Raten.'));
 for(const [id,label]of [['setup','Versuchsaufbau und zuvor festgelegte Kriterien'],['question','Meine Prüf- und Rückfrage'],['a','Antwort A · zunächst ohne Herkunft'],['b','Antwort B · zunächst ohne Herkunft'],['verdict','Urteil vor der Offenlegung · Begründung und Unsicherheit']])addNote(turing,label,'turing-'+id);
 const reveal=el('details');reveal.append(el('summary','Nach dem Urteil: Herkunft offenlegen und Urteil prüfen'));addNote(reveal,'Tatsächliche Herkunft von A und B','turing-origin');addNote(reveal,'Was ändere ich? Was bleibt über Verstehen unentschieden?','turing-revision');turing.append(reveal);dialog.append(turing);
 button(dialog,'Meine Perspektivnotizen als Datei sichern',()=>{const blob=new Blob([JSON.stringify({version:1,kind:'private-perspective-notes',notes},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='schachmaschine-perspektivnotizen.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 }
 openButton.onclick=()=>{returnFocus=document.activeElement;render();dialog.showModal();};dialog.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
 return {update(context,pov){current=context;perspective=pov;const toolbar=document.querySelector('.reading-tools');if(toolbar&&!openButton.isConnected)toolbar.append(openButton);const next=JSON.stringify([context.stage.id,context.state.opened,pov,context.room?.code,context.room?.epoch]);if(dialog.open&&next!==signature)render();signature=next;},hide(){decision.hide();if(dialog.open)dialog.close();}};
}
